### ISSUE TITLE
CNS*2022 satellite tutorials: set up registration form

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#101]
We need to set up a registration form. Here's what I had in mind:

- simple Google form
- information we collect:
  - e-mail addresses (for any urgent updates, and if we decide to keep zoom links limited to registrants)
  - ask if people want to be subscribed to our mailing list (check-box)
  - ask what sessions people are likely to attend: list all sessions with check-boxes: to get an idea of attendance
  - ask if people want to join the WG: additional information for this: institution/affiliation, github username to add folks to the [members page](https://ocns.github.io/SoftwareWG/pages/members.html)

For people that do not want to use Google forms, we'll also allow people to e-mail Shailesh and me to register with the information, and we'll fill the form in for them etc.

**Comment by sanjayankur31** [comment]
@OCNS/software-wg : thoughts? (also mailing our list now)

**Comment by brenthuisman** [comment]
If you want an alternative to Google Forms, https://framaforms.org is an option. Unfortunately the signup part seems to be French only, the rest is also English I think.

**Comment by sanjayankur31** [comment]
That looks good, I'll take a look to see what features it has, thanks!

@malinINCF : does the INCF have some form based infrastructure that could be used for this perhaps? (something quick and easy---if it requires lots of work on the infra side, it's not worth it).

We could also use the OCNS memberclicks instance I guess, but I can't remember if it allows non-members etc. to fill in forms etc., and I *think* @appukuttan-shailesh is on leave/holiday for a bit, so we may not be able to get that set up soon enough

**Comment by sanjayankur31** [comment]
Quick note: framaforms is limited to 1000 responses (I don't know if we expect more than 1000 folks to turn up though---I *think* we did have >1000 registrants when CNS was online + free)

**Comment by sanjayankur31** [comment]
I've set up a simple form on framaforms [here](https://framaforms.org/incfocns-software-wg-cns2022-satellite-tutorials-registration-1654593600). Could you folks please check it out (and submit it) to see if it looks OK? I can remove your submissions before the announcement.

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg : I'd like to send out the announcement e-mails for registration at the end of the working day today. If you could all please register to test the form and the e-mail confirmation, that'll be very helpful.

The form is [here](https://framaforms.org/incfocns-software-wg-cns2022-satellite-tutorials-registration-1654593600)

**Comment by mstimberg** [comment]
Registration + email confirmation worked for me :+1:

**Comment by tnowotny** [comment]
same here

**Comment by sanjayankur31** [comment]
Thanks for all your feedback everyone. I've made any required changes and will send the e-mails out now.

**Comment by brenthuisman** [comment]
Unfortunately the UI is still all French ;)

**Comment by sanjayankur31** [comment]
That cannot be changed from the looks of it (or i havent been able to
figure out how), so I've added text to make sure folks know what the submit
button is. The form itself is all English, so should be fine. Otherwise
folks can contact me and I'll fill it out for them..

**Comment by mstimberg** [comment]
Oh, I had kind of assumed the form was French because I was filling it out from France :smile: . Apparently you can change the text of the submit button at least: 
> Formulaire > Paramètres avancés du formulaire > Paramètres avancés > Texte du bouton de soumission (Par défaut le bouton de soumission de ce formulaire aura le label Soumettre . Entrer un nouveau label si vous voulez le changer).

**Comment by brenthuisman** [comment]
It's not the only service Framasoft have set up and disabled everything but French (Yakforms comes with at least also English). Small price for having a great free and Free service, but, can be confusing if you don't speak (some) French.

**Comment by mstimberg** [comment]
I think they didn't really disable other languages. If I understood correctly, you have to install Yakforms/Drupal in a specific language – i.e. you cannot switch the language on a form-by-form basis but have to host one version for each language.

**Comment by sanjayankur31** [comment]
> Oh, I had kind of assumed the form was French because I was filling it out from France smile . Apparently you can change the text of the submit button at least:
> 
> > Formulaire > Paramètres avancés du formulaire > Paramètres avancés > Texte du bouton de soumission (Par défaut le bouton de soumission de ce formulaire aura le label Soumettre . Entrer un nouveau label si vous voulez le changer).

Thanks for that! I hadn't managed to explore all that using translation yet. I've updated the submit button and the related text there now.
