### ISSUE TITLE
Next WG meeting: Wednesday 06 July, 2022: 0800 UTC + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#107]
Hi @OCNS/software-wg the next meeting is on 6th of July.

Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see https://github.com/OCNS/SoftwareWG/issues/66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://hackmd.io/@sanjayankur31/SykigaHKc

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Also e-mailed the mailing list, although since it's website is down, I don't know if e-mails will be delivered.

**Comment by mstimberg** [comment]
> Also e-mailed the mailing list, although since its website is down, I don't know if e-mails will be delivered.

I got the mail, so the list itself seems still to be working.

**Comment by mstimberg** [comment]
PS: I will attend the 8:00 UTC meeting most likely.

**Comment by appukuttan-shailesh** [comment]
I too shall attend the 08:00 UTC meeting.

**Comment by sanjayankur31** [comment]
Thanks folks. I'll see you all tomorrow.

**Comment by mstimberg** [comment]
Apologies, I joined but could only hear half of what was said, my University's internet is having major issues atm. I might be able to join for the second session, though.

**Comment by sanjayankur31** [comment]
The next meeting slot is later today at 1700 UTC. Hope to see some of you there.

**Comment by sanjayankur31** [comment]
Minutes published and sent to ML:

https://ocns.github.io/SoftwareWG/2022/07/07/wg-meeting-06-july-2022.html
