### ISSUE TITLE
Next open WG meeting: Thursday 11 August, 2022: 0800 UTC + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#110]
Hi @OCNS/software-wg the next meeting is on 11th of August.

Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see https://github.com/OCNS/SoftwareWG/issues/66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://ocns.github.io/SoftwareWG/2022/07/07/wg-meeting-06-july-2022.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Agenda items:

- tasks from last meeting
- upcoming INCF assembly tasks (and help required!)
- bernstein conference related discussion
- satellite tutorial follow ups
- pending tasks/issue follow ups
- plans for more dev sessions/software highlights/tutorials

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg 

Reminder for the 0800 UTC meeting, which will start in about an hour and a half.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
I've started the meeting folks, please join whenever convenient

**Comment by appukuttan-shailesh** [comment]
I am travelling for work and won't be able to join either of the sessions today. Will follow the minutes of the meeting later.

**Comment by sanjayankur31** [comment]
Sounds good.

We had a great 0800 meeting with all new faces (apart from me!). The minutes document is here:

https://hackmd.io/@sanjayankur31/By2bPNfCq

**Comment by ErbB4** [comment]
Thank you for the minutes! I will try to join the meeting next time.
Han LU

**Comment by sanjayankur31** [comment]
Hi https://github.com/orgs/OCNS/teams/software-wg

Reminder for the 1700 UTC meeting, which will start in ~ 10 minutes

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Thanks for attending the meeting everyone, it was great to chat with you all.

Please do go over the minutes folks and add more information/notes there. I'll publish them on our website at the end of next week on Friday Aug 19.
