### ISSUE TITLE
Dev session: Brian2CUDA

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#114]
A dev session on Brian2CUDA would be great for us all to learn how it works and so on. I'm speaking to Denis over e-mail to organise this.

https://github.com/brian-team/brian2cuda

**Comment by sanjayankur31** [comment]
Suggested time: Thursday, November 3rd, 1600 UTC

**Comment by sanjayankur31** [comment]
Now announced on various mailing lists. If you don't see the announcement anywhere, please do let me know:

https://lists.incf.org/pipermail/incf-ocns-software-wg/2022-October/000012.html

**Comment by sanjayankur31** [comment]
Hi @ocns-webmaster : a reminder of today's dev session. I hope to see you there :+1:

**Comment by sanjayankur31** [comment]
I've started the zoom meeting folks, please join at your convenience @OCNS/software-wg

**Comment by sanjayankur31** [comment]
Zoom link for your convenience: https://ucl.zoom.us/j/95692778384?pwd=VldIQ3hPTU1zczNpYjQxSSt4Z25xdz09

**Comment by cmahapatra97** [comment]
Is there any meeting passcode ?
-------------------------------------------------------------------------------------------------
Chitaranjan Mahapatra

**Comment by mstimberg** [comment]
I might be a few minutes late, no need to wait for me obviously.

**Comment by sanjayankur31** [comment]
> Is there any meeting passcode ? ------------------------------------------------------------------------------------------------- Chitaranjan 

Hi @cmahapatra97 , sorry I didn't see this yesterday. The zoom link should just have worked, it already has the pass code included in it. The calendar invite should also have the pass code in it if you need that separately (the calendar invite is generated from zoom)

**Comment by sanjayankur31** [comment]
Here are the recordings folks, I'll send them off to the INCF for uploading on to their platforms in a bit:

https://ucl.zoom.us/rec/share/88Em-VBxsaQoVklH49MFQnaJXcC1p_GtGPyb9Z9pdGE5zBPtDrLhxIeJ7K2FhdY.3x0ff3jfzyttNPM6

**Comment by sanjayankur31** [comment]
Recordings sent, should be up in sometime. I'll close this ticket now.
