### ISSUE TITLE
Next open SoftwareWG meeting: Monday 10th October, 0800 + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#115]
Hi @OCNS/software-wg the next meeting is on 10th of October. 

Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see https://github.com/OCNS/SoftwareWG/issues/66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://ocns.github.io/SoftwareWG/2022/09/27/wg-meeting-19-september-2022.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Initial agenda:

- tasks from last meeting
- setting up task forces for our two longer term projects
  - software development guidelines: https://github.com/OCNS/SoftwareWG/issues/113
  - resource to allow users to select simulator to use: https://github.com/OCNS/SoftwareWG/issues/61

Please add more items you wish to discuss.

**Comment by sanjayankur31** [comment]
I've started the 0800 meeting @OCNS/software-wg , please join when convenient:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Here's the minutes document folks:

https://hackmd.io/@sanjayankur31/ryjiCH-Qj/edit

I'll see the rest of you in the evening.

**Comment by mstimberg** [comment]
> I'll see the rest of you in the evening.

I will join the second meeting, see you then.

**Comment by appukuttan-shailesh** [comment]
Hope to be back in time for the second meeting (or might connect via mobile if still in transit)

**Comment by sanjayankur31** [comment]
I've started the 1700 UTC call now folks, please join when convenient. We'll start at 1705 UTC:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by appukuttan-shailesh** [comment]
Sorry couldn't make it in time.... thanks for the minutes!
