### ISSUE TITLE
Call for participation: task force to work on Software development guidelines/best practices

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#116]
Please see this ticket for more information on the task:

https://github.com/OCNS/SoftwareWG/issues/113

We would like to set up a task force to deliver the first version of these software development guidelines/best practices. Please comment on this ticket if you would like to join the task force.

**Comment by dissagaliyeva** [comment]
Hi Ankur! I'd like to join :)

**Comment by cmahapatra97** [comment]
Hi Ankur,
 I am interested in joining the task force. I will volunteer a couple of hours per week on the activities of the task force. 
Best,
Chitaranjan

**Comment by sanjayankur31** [comment]
Thanks @dissagaliyeva , @cmahapatra97 . Sounds great. We'll leave this open for a week or two to allow folks more time to decide, and then the task forces can start their work.

**Comment by heitorsf** [comment]
Hello, I would like to join this task force. I can volunteer a couple of hours per week, too.
Cheers,
Heitor

**Comment by mstimberg** [comment]
I'd be happy to get involved as well :tada:

**Comment by sanjayankur31** [comment]
I'd like to be involved in this one as well :100:

**Comment by lab-catrina** [comment]
Hi, I would like to help

**Comment by shayan823** [comment]
Hi Ankur,

I would like to get involved. I can volunteer a couple of hours per week.

Regards,
Shayan Shafquat

**Comment by anilbey** [comment]
I'm also interested in participating.

**Comment by sanjayankur31** [comment]
Thanks folks. We'll wait till the end of this week, 23 October, for more people to join, and then proceed.

I see we've got >10 folks here, but only 3 in #117 for the quick resources to help users pick simulation tools. Would some folks like to perhaps work on #117 instead? That's something that I'd perhaps consider slightly more important in the short-term, and I'd also expect a deliverable there earlier than for the guidelines here.

**Comment by sanjayankur31** [comment]
Thanks for all your interest @mstimberg @anilbey @lab-catrina @shayan823 @mandarmp @rahafai @heitorsf @cmahapatra97 @dissagaliyeva 

Please fill out this whenisgood as soon as possible, and latest by the end of this week (28th October) so we can have an initial meeting next week to get things started:

http://whenisgood.net/qp7mnk5

Please remember to select your time zone when filling it in. And, please select all the slots that work for you. The more slots we all select, the more likely we are able to find one that works for us all.

**Comment by sanjayankur31** [comment]
Hi folks, just a reminder. Please fill in the whenisgood if you haven't yet:

http://whenisgood.net/qp7mnk5

**Comment by sanjayankur31** [comment]
Hi folks, thanks for filling in the whenisgood. Not surprisingly, we haven't managed to find a time that works for everyone. In fact, the best we could do is fit 4-5 of us on November 2 at 1700 UTC. Sorry about that. We'll keep meeting notes etc. as usual, and we'll need to decide on an async discussion platform too.

This time, we'll meet on our Jitsi link again:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Calendar invite here (you'll need to rename the file to remove the `.txt` at the end to import it to your calendar app).

[software-wg-guidelines-taskforce-initial.ics.txt](https://github.com/OCNS/SoftwareWG/files/9900294/software-wg-guidelines-taskforce-initial.ics.txt)

I'll see you all there.

**Comment by sanjayankur31** [comment]
Hi folks,

A reminder of today's meeting. Here's the jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Cheers!

**Comment by mstimberg** [comment]
Apologies, unfortunately I won't be able to make it to today's meeting (but still interested in contributing of course). Have a good meeting everyone!

**Comment by sanjayankur31** [comment]
I've started the Jitsi meeting now folks, please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

The shared meeting notes doc is here: https://hackmd.io/@sanjayankur31/B1TokmxBi

**Comment by sanjayankur31** [comment]
Thanks for the meeting folks. Please go through the meeting notes document for the complete logs:

https://hackmd.io/@sanjayankur31/B1TokmxBi

The primary action item from today's meeting is:

- ACTION: task force members go through resources to make example lists of what items they think would be useful. The idea is to go through the lists to see why they are insufficient (if they are insufficient), and to come up with individual lists of items that we will compare in the next meeting.

We will compare our lists in the next meeting in two weeks to get a better understanding of what we think the list should contain, and who our target audience will be. (@cmahapatra97 will set up a new doodle for us to find a meeting time in the week starting November 14.)

Please feel free to write your lists wherever, and we can collate them all in the shared document before the next meeting.

**Comment by dissagaliyeva** [comment]
@mstimberg I'm totally fine with the same time as today :) however, I'm ok with changing it if people can't make it

**Comment by sanjayankur31** [comment]
@cmahapatra97 : I think you are going to send out a doodle at some point for us to find the next meeting time?

**Comment by mstimberg** [comment]
:bell: Any news? Do you think there will be another meeting before people head off for end-of-year vacations?

**Comment by cmahapatra97** [comment]
Dear all,
Please poll your preferred slot.
https://doodle.com/meeting/participate/id/ep85QV2e
Thank you.
Chitaranjan
-------------------------------------------------------------------------------------------------
Chitaranjan Mahapatra

**Comment by cmahapatra97** [comment]
Hey, we can reschedule it. Let me know your preferred time.

-------------------------------------------------------------------------------------------------
Chitaranjan Mahapatra

**Comment by mstimberg** [comment]
> Hey, we can reschedule it. Let me know your preferred time.

For me, it would be much easier to schedule something during the (European) day. But my schedule in the coming days is already quite packed, especially in the afternoons. I don't know the timezones for the other members, maybe there simply isn't a solution that works for everyone…

**Comment by brenthuisman** [comment]
If it's not too late to chip in: someone pointed me to Erik de Schutter's [Why Are Computational Neuroscience and Systems Biology So Separate?](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000078), which compares software engineering culture of two different areas of biology (neuroscience and systems biology), and I recognize quite a few things that could be impacted by a set of dev guidelines (data sharing is much more developed in system biology e.g.). [Chapter 4](https://archiv.ub.uni-heidelberg.de/volltextserver/30261/1/obreitwi-phd-final_v2.pdf) of the thesis of a student of a colleague also attempts to come up with such guidelines based on literature review.

The guidelines we could extract are less so about the specifics of tooling, but are more general, more social: what constitutes the sharing of a model? How far do you go with providing instructions for reproduction? At some point, the HBP had very specific ideas about this, which unfortunately did not work out due to a community that couldn't see the point. Guidelines with all/some of this in mind could be the start of an improvement, not just on the level of code formatting and repo structuring, but further.

Because it would be lazy to tell you what to do without me exerting effort, I'm happy to join a next meet.

**Comment by sanjayankur31** [comment]
We've started the cookbook repository here. Please do that a look and add your commonly used snippets there. We'll discuss the creation of a new taskforce to maintain the cook book in a bit:

https://github.com/OCNS/CompNeuroCookBook


I'm going to close this issue now.
