### ISSUE TITLE
Next open SoftwareWG meeting: Tuesday 8th November, 0800 + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#119]
Hi @OCNS/software-wg the next meeting is on 8th of November.

Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see https://github.com/OCNS/SoftwareWG/issues/66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://ocns.github.io/SoftwareWG/2022/10/17/wg-meeting-10-october-2022.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
The agenda I have so far is:

- go over tasks from last meeting

I think it's too soon to discuss the task forces, so that can wait for next month or later when they're prepared to discuss their work with the WG.

Anything else, folks?

**Comment by brenthuisman** [comment]
My schedule makes it hard to attend these days, sorry! One thing though: I guess the title and date should be Tuesday the 8th.

**Comment by sanjayankur31** [comment]
Oo, yes! I'll correct that right away.

**Comment by sanjayankur31** [comment]
I've started the meeting now folks, please join at your convenience. We'll start at 5 past 0800 UTC. 

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by appukuttan-shailesh** [comment]
I will be joining the 17h00 call. See you all in a bit.

**Comment by sanjayankur31** [comment]
I've started the evening call folks, please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Thanks for attending the meeting folks. There wasn't a lot of new tasks/discussion this time. We primarily discussed the work the task forces are doing. You can follow their progress on the individual tickets:

- #116 
- #117 
I'll close this ticket now.
