### ISSUE TITLE
Next open SoftwareWG meeting: Monday 16 January, 0800 + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#120]
Hi @OCNS/software-wg .

Happy new year!

The next meeting will be on Monday 16 January. Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see #66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from November's meeting are here:

https://github.com/OCNS/SoftwareWG/issues/119

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Initial bits I think we need to discuss:

- task force updates
- ideas for sessions (dev sessions, hightlights etc.)
- initial discussion on whether or not we want to host satellite tutorials along with (before?) CNS*2023 (the conference is in Leipzig from July 15-19)

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg : a reminder for the meeting on Monday at 0800 and 1700 UTC. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

See you all there.

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg. I've started the 0800 meeting call now. Please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by mstimberg** [comment]
Sorry for the late notice, but I'll join the meeting later today, see you there :wave:

**Comment by appukuttan-shailesh** [comment]
I am unfortunately returning from holidays and in transit at the moment, reaching only later tonight, so would be unable to join either of the sessions this time.

**Comment by sanjayankur31** [comment]
Hi folks, I've started the 1700 UTC meeting call now. Please join at your convenience. We usually start at 5 past to give everyone time to join.

Meeting link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Thanks for coming everyone. Here is the meeting logs document @OCNS/software-wg :

https://hackmd.io/tHrCfiANQwySRffbRcctZQ

I'll also clean it up and send it to the list etc.

**Comment by cmahapatra97** [comment]
Hi all,

Please poll your date (at 1700 UTC) for the next meeting.
*https://doodle.com/meeting/participate/id/dyww45ga
<https://doodle.com/meeting/participate/id/dyww45ga>*

Thanks.
Chitaranjan
-------------------------------------------------------------------------------------------------
Chitaranjan Mahapatra

**Comment by sanjayankur31** [comment]
Sorry @cmahapatra97 : what meeting is this for? The software WG meetings will remain at 0800 and 1700. I think you meant to set up a meeting for the guidelines task force (#116)?

**Comment by sanjayankur31** [comment]
> My apologies for the inconvenience. The meeting poll is for the guidelines task force (#116 <#116>).

Sorry @cmahapatra97 : I wasn't able to manage either of the two slots.

When you have a minute, would you please:

- set up a new doodle with more slots (not just 1 hour each on two different days---that's very little choice for a global community) maybe for the week starting 13 Feb? (CC: @anilbey )
- post the link to #116
