### ISSUE TITLE
Clarify communication channels

### ISSUE THREAD

**Issue by mstimberg** [OCNS/SoftwareWG#122]
Hi everyone,
I came across the following statement on the [contact section of our website](https://ocns.github.io/SoftwareWG/pages/contact.html):
> The primary mode of communication for the working group will remain on Neurostars. However, the regular developer sessions will be supplemented with virtual working group meetings to allow our global membership to communicate with each other.

That should probably say *GitHub* for the primary communication channel, no? And maybe we don't need to say "will be supplemented" anymore, since we are already having regular working group meetings.

**Comment by sanjayankur31** [comment]
Yeh, sorry, forgot to update that. Could you please tweak it and push a fix if you have a minute? (no need for a PR for such a simple change)

**Comment by mstimberg** [comment]
Sure thing, just wanted to make sure I didn't misunderstand anything.
