### ISSUE TITLE
CoC for WG

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#123]
We don't have an explicit CoC for the WG, and we really should.

I propose we adopt the OCNS CoC for a start, and then make any further tweaks if required. The bit we do need to change is how it'll be enforced---I expect the chairs will be responsible for that particular bit.

https://www.cnsorg.org/code-of-conduct

Please take a look at let us know what you think, and we'll add the necessary info to our website when we're ready.

**Comment by appukuttan-shailesh** [comment]
Thanks @sanjayankur31 
I agree, this can be used as a starting point, and can be adapted later as and when required.

**Comment by brenthuisman** [comment]
The main thing/change is to have a contact point and one or more people who will handle any inquiries to it. Could that be the OCNS contact point and people? That would have the advantage of having some distance from the people commonly in this workgroup.
