### ISSUE TITLE
RFC: WG presence at CNS 2023

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#125]
Hi @OCNS/software-wg 

This is a follow up from the initial discussion at the [January meeting](https://ocns.github.io/SoftwareWG/2023/02/01/wg-meeting-16-january-2023.html). 

The question is: what, if anything, do we do at [CNS 2023](https://www.cnsorg.org/cns-2023-quick).

## Context

We did [a whole week of satellite tutorials at CNS 2022 last year](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html). These were free to register for, and open to everyone. Organising them did take a little bit of work---communicating with tutors, scheduling them, announcing them, setting up all the meetings etc. We had great registration numbers: >250 registrants, but we had low turnout: ~10 per session.

The low turnout could've been for a number of reasons---lack of daily reminders is one, zoom fatigue is another, availability of lots of documentation and video tutorials that users can follow in their own time is another. We sent a short survey to all registrants and got very few responses (a subset of attendees), but those that did respond generally indicated that they'd be happy to pay a small registratin fee.

So, we, as the WG need to decide if we'll do another round of satellite tutorials this year. If we do, the plan is to make a few tweaks to learn from our experience last year:

- require some registration to filter out people that register but are unlikely to attend; registration fees will be low (~20$) and can be waived
- use something like [Sched](https://sched.com) for scheduling the sessions; this requires someone to fund us up front; sched allows users to select what sessions they want to attend and then it sends them daily reminders and so on.
- hopefully INCF/OCNS will fund this, and set up a registration form on their infrastructure---the money earned from registration will go to them.

The larger question is: are online tutorials, and a full week of them covering lots of tools, still relevant/useful to the community? A general feeling does seem to be that because we're all working hard at writing good documentation and tutorials (often video based), users are happier using these resources when they need them (on-demand) rather than sitting through a whole week learning lots of tools that they may or may not need in the short-term future. There are also initiatives like [NeuroMatch Academy](https://compneuro.neuromatch.io/tutorials/intro.html) that are solely focused on training and do a much better job than what we can manage---although, they're not software specific from what I know.

## Alternatives

If we think such a week of tutorials is not the way to go, do we want to do something else? If yes, what?

Initial ideas (in no particular order):

- do one hour software highlights---these are shorter and introduce people to tools; some of these tools will do in-person tutorials at CNS, so they'll act as a gateway to them
- software wg open day with a mix of user and dev focussed sessions, open to everyone to attend
- reproduction projects
  - tutors (tool devs) list some models that they would like reproduced in their simulators
  - "students" work with them to reproduce them
  - submit for review to [Rescience](http://rescience.github.io/)
  - Issue: probably not doable in a day, so if done, will be a longer term project requiring multiple meetings
- internships
  - usually require some buy in from institutions, so not easy to do

So, please comment here with your views. We'd like to make a decision and get started with the necessary organisation ASAP. Please also share this with your labs/colleagues---all input is welcome.

**Comment by brenthuisman** [comment]
Thanks for bringing the discussion on the usefulness up, @sanjayankur31. First off: the satellite sessions, are they in addition to the tutorials and workshops I received an invite for yesterday? I was under the impression those will be in person. If they are in addition, given the low turnout of online sessions, I'm tending to foregoing them.

Setting up the infrastructure of an event like previous years sound like too much effort for the outcome to me. Without an idea for getting the attendance up, I wouldn't do that. Ideally something more workshoppy/hackathony would be nice, but my experience is also that these workshop mostly attract new students, of which at least half has no significant programming experience. That means coding is off the table (my own sessions were designed to be interactive, but they never are). Do others experience a similar ratio?

**Comment by sanjayankur31** [comment]
> Thanks for bringing the discussion on the usefulness up, @sanjayankur31. First off: the satellite sessions, are they in addition to the tutorials and workshops I received an invite for yesterday? I was under the impression those will be in person. If they are in addition, given the low turnout of online sessions, I'm tending to foregoing them.

Yes, these are in addition to the in-person sessions, since the in-person sessions are limited to those that are able to attend the conference. 

> Setting up the infrastructure of an event like previous years sound like too much effort for the outcome to me. Without an idea for getting the attendance up, I wouldn't do that. Ideally something more workshoppy/hackathony would be nice, but my experience is also that these workshop mostly attract new students, of which at least half has no significant programming experience. That means coding is off the table (my own sessions were designed to be interactive, but they never are). Do others experience a similar ratio?

We used Jupyter notebooks over OSB for our NeuroML sessions. They were meant to be interactive, and I think a few folks did follow along but yeh, something workshoppy/hackathony would be nice. I'm wondering if reproducing models using our tools would attract more folks, but then, that's quite a bit of work.

**Comment by mstimberg** [comment]
I agree with @brenthuisman here that setting up a full set of online tutorials is probably too much work for too little outcome, in particular given that some of us will be involved in an in-person workshop/tutorial (more so than last year when CNS was in Australia). 

Reproduction projects sound nice, but also not sure how feasible with limited time/resources (and possibly student skill). 

From my point of view, two things could be feasible/interesting to do:
* Some kind of Software WG event (could even be somewhat hackathonish, e.g. around the taskforce projects) that is not only aimed at attracting new active members to the WG, but also at simply bringing WG members together. We have our regular meetings and dev sessions, but only a few members show up each time. This is of course normal (schedules, etc.) – but maybe with a full or half day scheduled a long time in advance, more members might be able to show up?
* Something aimed at beginners in comp neurosci that would be orthogonal to the tutorials at CNS (which usually go into detail about specific tools/approaches), e.g. sessions about very general topics (say, how to organize files/folders for a research project, store them in git, etc.; how to make "publication-ready" plots; …), sessions that give a very quick overview of different simulators/frontends, etc.

Actually, we might consider proposing the first option as an official workshop for CNS? But for staying in line with the principles of the WG, we'd need to somehow negotiate to make it hybrid and open to people who did not register for CNS, not sure whether that's feasible.

**Comment by sanjayankur31** [comment]
The general feeling at the [meeting](https://hackmd.io/@sanjayankur31/r13sAn_Ti) was to not do satellite tutorials, and instead continue with dev sessions/high lights and the sort. I expect the different simulator communities will do their tutorials/workshops at CNS in person this year, so we leave that bit at that.

How about:

- "computational modelling best practices, tips and tricks" workshop or tutorial as a Software WG event that could include a mix of beginner level sessions (git? datalad?) and general bits related to the modelling life cycle?
- an informal WG get together at CNS, maybe on one of the evenings when there isn't the dinner/party?

The second one only materialises if folks are up for it, of course, since we'll need instructors. Thoughts?

Note: workshop submission deadline:  15th of April, 2023; tutorial submission deadline: April 22, 2023 (11:59 EST)

**Comment by appukuttan-shailesh** [comment]
I have sent an email to the OCNS board inquiring about the tutorials and workshops under consideration for CNS*2023. Hopefully we will have some info to discuss at the next WG meeting (in the third week of April).

**Comment by sanjayankur31** [comment]
PSA: Any WG members that need visas to travel to Germany should apply ASAP. Here in London, there are no application appointments available till the end of may at all, and they haven't released appointments for June yet. :roll_eyes:

**Comment by appukuttan-shailesh** [comment]
Haven't received any update regarding the workshops and tutorials at CNS*2023 yet. There have been inquiries from others too more recently. Might take a bit longer to have some news on this.

**Comment by mstimberg** [comment]
This issue has been quiet for a while, but I think we agreed to 1) not do any workshop/tutorial and 2) to meet in some informal way at CNS.

Maybe everyone from the @OCNS/software-wg could briefly comment in this issue whether they will be present at the CNS meeting and if yes, whether they are presenting anything (preferably with links to the sched.com instance)

**Comment by mstimberg** [comment]
I'll start :blush:
I will be at CNS (for tutorials and main meeting, but not for the workshops), and I'll present a tutorial (together with @mpgl and @spirosChv) and a poster.
Looking forward to seeing you there :beers: !

Sched links:
- Tutorial: https://cns2023.sched.com/event/1ND2z/t03-modeling-dendritic-computations-in-spiking-neural-networks-with-brian-2-and-dendrify 
- Poster: https://cns2023.sched.com/event/1NYYs/p195-brian-in-the-browser-running-neural-simulations-with-webassembly

**Comment by ree-gupta** [comment]
Hey all! I will be at CNS (for tutorials, main meeting and most of the workshops) and will be presenting part of a tutorial and a poster.

Sched links:

- [Tutorial](https://cns2023.sched.com/event/1ND5W/t08-using-open-tools-to-build-efficient-workflows-for-data-access-management-and-analysis)
- [Poster](https://cns2023.sched.com/event/1NYZk/p213-tools-and-services-for-managing-and-sharing-research-data-facilitating-data-integration-and-collaboration)

Looking forward! 😄

**Comment by cmahapatra97** [comment]
Dear all,

I will also be at CNS 2023 from 15th July to 18th July for both tutorial
and poster.

   - Tutorial:
   https://cns2023.sched.com/event/1NCgt/t07-hands-on-tutorial-on-pynn-a-simulator-independent-language-for-building-neuronal-network-models
   - Poster:
   https://cns2023.sched.com/event/1O6u3/p264-computational-modelling-of-the-pathway-between-dopamine-receptors-and-ca2-channels-in-layer-ii-stellate-cells

See you all in Leipzig.

Chitaranjan
-------------------------------------------------------------------------------------------------
Chitaranjan Mohapatra

**Comment by sanjayankur31** [comment]
I'll make it to CNS this year too (Padraig will also be there). We've got a few posters this time and will be attending the various tutorials/workshops to see where NeuroML and OSB can fit in (as usual :))

- [MDF](https://cns2023.sched.com/event/1NYQn/p028-integrating-model-development-across-computational-neuroscience-cognitive-science-and-machine-learning-using-the-model-description-format-mdf)
- [NeuroML and OSB](https://cns2023.sched.com/event/1NYSO/p061-facilitating-the-development-of-data-driven-standardised-cortical-models-in-the-cloud-using-neuroml-and-open-source-brain-v2)
- [Ih channel modelling](https://cns2023.sched.com/event/1NYW1/p136-effects-of-ih-channel-modulation-on-excitability-and-dendritic-integration-in-layer-v-pyramidal-cells-in-health-and-in-schizophrenia)

(I somehow have two profiles on Sched, and these are linked to the unclaimed profile. I've requested the webmaster to merge them if possible)

**Comment by clinssen** [comment]
Hi, me and several colleagues will be presenting a full-day NEST Simulator tutorial. Please see here for details: https://cns2023.sched.com/event/1NCc8/t02-from-single-cell-modeling-to-large-scale-network-dynamics-with-nest-simulator

**Comment by sanjayankur31** [comment]
Great to see so many of you coming. 

Should we get together towards the end of the welcome reception on Saturday evening, at 8PM, and we can see if we want to go for dinner/drinks or something after? We can also then discuss what else we want to do formally/informally at the conference and in the future?

https://sched.co/1Kd5x

**Comment by cmahapatra97** [comment]
Fine, I am in.

Best,
Chitaranjan
-------------------------------------------------------------------------------------------------
Chitaranjan Mohapatra
