### ISSUE TITLE
Next open SoftwareWG meeting: Tuesday 14 February, 0800 + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#126]
Hi @OCNS/software-wg .

The next meeting will be on Tuesday 14 February. Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see #66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from January's meeting are here:

https://ocns.github.io/SoftwareWG/2023/02/01/wg-meeting-16-january-2023.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by appukuttan-shailesh** [comment]
I intend to attend the morning session.

As part of the agenda, we can discuss:
- plans for CNS*2023 (if any)
- about having a new co-chair to replace myself. I have been finding it difficult in recent months to devote much time to the admin activities of the group, and it would therefore be useful to have someone else step-up and help manage the WG. I will naturally continue to contribute as a member of the WG. Forming the task forces (for the two ongoing tasks) was a nice example of how some of the workload could be distributed and managed.

**Comment by appukuttan-shailesh** [comment]
@OCNS/software-wg .... first meeting starting in 5 minutes.

**Comment by sanjayankur31** [comment]
I was just about to post :D

I've started the call now folks, please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Notes document: https://hackmd.io/@sanjayankur31/r13sAn_Ti

Two additional items for the agenda:

- CoC
    - https://github.com/OCNS/SoftwareWG/issues/123
- Task force updates

**Comment by mstimberg** [comment]
Sorry about the late notice, but I'll be there for the second meeting :blush:

**Comment by sanjayankur31** [comment]
@OCNS/software-wg I've started the evening meeting call now folks, please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab
