### ISSUE TITLE
Next open SoftwareWG meeting: Wednesday 15 March, 0800 + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#128]
Hi @OCNS/software-wg .

The next meeting will be on Wednesday 15 March. Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see #66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from February's meeting are here:

https://ocns.github.io/SoftwareWG/2023/03/08/wg-meeting-14-february-2023.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Agenda items:

- Tasks from last meeting
- RFC CNS2023: #125 
- Tasks force updates

**Comment by appukuttan-shailesh** [comment]
Planning to attend the morning session.

**Comment by mstimberg** [comment]
I'll try to be there for the morning session as well.

**Comment by sanjayankur31** [comment]
I've started the call now folks, please join at your convenience. We'll start at 0805 UTC:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Meeting notes document is here folks:

https://hackmd.io/@sanjayankur31/rkgMjlke2

(Please add anything I may have missed)

**Comment by sanjayankur31** [comment]
I've started the 1700 meeting now folks, please join at your convenience:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab
