### ISSUE TITLE
Call for self-nominations for co-chairing the WG

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#129]
As previously described [here](https://github.com/OCNS/SoftwareWG/issues/126#issuecomment-1422455361), we would like to have a new co-chair to help manage and steer this working group. I have been finding it difficult in recent months to devote much time to the admin activities of the group, and it would therefore be useful to have someone else step-up and help manage the WG alongside @sanjayankur31.

We request members of the WG (@OCNS/software-wg) to self-nominate and express their interest in taking up this role. To do so, you can send an email to Ankur (ankur DOT sinha AT ucl DOT ac DOT uk) or me (appukuttan DOT shailesh AT gmail DOT com). Feel free to contact us if you have any questions regarding the responsibilities that the role entails.

**Deadline for self-nominations: March 31, 2023**

**Comment by appukuttan-shailesh** [comment]
@OCNS/software-wg : Here is a brief overview of some of the responsiblities that the role entails:

- help organize the monthly meetings to plan future WG events and activities
- help setup and coordinate task forces
- contact developers for prospective dev or showcase sessions
- coordinate with confirmed devs to organize these sessions
- publicize WG events and sessions via mailing lists
- interact with OCNS and INCF as required to further WG objectives
- keep the WG members of various developments via GitHub and the WG mailing lists

@sanjayankur31 can add/edit this list.

**Comment by sanjayankur31** [comment]
I think this is complete, I can't think of anything else. :+1:

**Comment by mstimberg** [comment]
Thank you very much @appukuttan-shailesh for the warm words, and of course for the last two years of co-charing the working group. You and @sanjayankur31 really did a great job of setting this thing up and keeping the momentum going. I am honoured to take over – let's see whether I fumble the baton handover right away ;)
My first action as a chair :drum:… closing this issue!
