### ISSUE TITLE
Deploy broken: github-actions bot does not have write permissions to repo

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#136]
Our deployment here is currently broken because github-actions bot does not have write permissions to the repository. @appukuttan-shailesh : I think you need to modify the permissions at the organizational level to fix this. I can't seem to enable it only for the repository (even though I'm an admin for the OCNS org?):

https://github.com/OCNS/SoftwareWG/settings/actions -> I cannot select "read and write permissions" in "workflow permissions". 

Organizational policies described here:

https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#enforcing-a-policy-for-workflow-permissions-in-your-enterprise

**Comment by sanjayankur31** [comment]
For reference, error from a GH action:

```
ghp-import -m "Generate Pelican site" -b gh-pages "/home/runner/work/SoftwareWG/SoftwareWG/output"
git push origin gh-pages --force
remote: Permission to OCNS/SoftwareWG.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/OCNS/SoftwareWG/': The requested URL returned error: 403
make: *** [Makefile:82: github] Error 128
Error: Process completed with exit code 2.
```

https://github.com/OCNS/SoftwareWG/actions/runs/5585615878/jobs/10208579428

**Comment by appukuttan-shailesh** [comment]
Should be fixed now both at the org level and for this repo as well.

**Comment by sanjayankur31** [comment]
Thanks, works now :+1:
