### ISSUE TITLE
Presence at INCF assembly

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#18]
Hi folks, the Neuroinformatics assembly starts on 19th April. What do we want to do there?
I'd think it's a good place to at least have our next WG meeting.

@malinINCF : would you have some suggestions please?

https://neuroinformatics.incf.org/2021/program-at-a-glance

(Once we have some ideas to start with, we can file tickets related to tasks and work on them)

CC: @OCNS/software-wg

**Comment by sanjayankur31** [comment]
@malinINCF said:

> Definitely a poster, I think - posters will stay up the whole time and interested people can book slots to discuss "in person".
> 
> Otherwise, at least a few group members attending the session on FAIR in comp neuro is probably good, I am not updated yet exactly on what will go in it. Also, if you want a satellite or parallell meeting, that should be easy to arrange.

**Comment by sanjayankur31** [comment]
Hi folks,

Sorry it's rather last minute. Here's an abstract based on our general goals to submit to the INCF Assembly. Could you please take a look and suggest any changes when you have 2 minutes to spare?

https://docs.google.com/document/d/1SLtnYvsn38p14uBHjtZSHR3B9DMnJQaBSsAUdOM-0T0/edit?usp=sharing

I've listed everyone that is listed on our website as an author there. Please feel free to edit that information also.

**Comment by joewgraham** [comment]
It looks great.  I made a couple minor suggestions.

**Comment by malinsandstrom** [comment]
Looks good, Ankur! I have made some minor edits for clarity - for instance, at INCF we try to say "software tools" because many outside of the community do not realise we are not referring to physical, actual tools. Also, ***tool** developers* is clearer to outsiders who might not immediately realize what the developers are developing. Feel free to decline any of my suggestions.

**Comment by appukuttan-shailesh** [comment]
Thanks Ankur for starting this off (esp since we just have a day left for submission). The abstract conveys our purpose quite well, which is probably our primary aim at this stage. I have made some minor edits to the document.

Regarding the authorship, we should probably ask all those interested to post here their approval of the abstract and confirmation to have them included as a co-author (just as a formal nod).... just my thoughts.

**Comment by ChristophMetzner** [comment]
Thanks Ankur! Looks very good!

**Comment by sanjayankur31** [comment]
> Regarding the authorship, we should probably ask all those interested to post here their approval of the abstract and confirmation to have them included as a co-author (as a formal nod).... just my thoughts.

Yeh, that's the idea behind this ticket, and the post on Neurostars. The question really is whether it's opt-in or opt-out: if it's opt-in then only people that explicitly respond are included; if it's opt-out then everyone is in by default but must explicitly be asked to be removed.

In general, since this is a volunteer working group, i.e., people on the list have explicitly voluntarily said that they want to be part of it, I lean towards opt-out.

**Comment by sanjayankur31** [comment]
> Looks good, Ankur! I have made some minor edits for clarity - for instance, at INCF we try to say "software tools" because many outside of the community do not realise we are not referring to physical, actual tools. Also, _**tool** developers_ is clearer to outsiders who might not immediately realize what the developers are developing. Feel free to decline any of my suggestions.

Makes sense. Thanks very much. I'll wait till later in the day and then consolidate all changes.

**Comment by sanjayankur31** [comment]
Noting: @stewart-heitmann  responded to say it looks good

**Comment by appukuttan-shailesh** [comment]
> Yeh, that's the idea behind this ticket, and the post on Neurostars. The question really is whether it's opt-in or opt-out: if it's opt-in then only people that explicitly respond are included; if it's opt-out then everyone is in by default but must explicitly be asked to be removed.
> 
> In general, since this is a volunteer working group, i.e., people on the list have explicitly voluntarily said that they want to be part of it, I lean towards opt-out. The idea is that any one that has contributed to our activities: dev sessions or just engaged in discussions on any of our platforms, etc. should be given credit for the time + resources they've spent. It should all count.

I don't have a strong preference for either approaches. But since organizers and publishers typically ask confirmation for something akin to
>"We confirm that the submission has been read and approved by all named authors..."

it might be useful to consider an "opt-in" approach just to be in the clear.

I totally agree that everyone who has contributed, in one way or the other, deserves to be credited for the same. And with that in mind we should offer them all co-authorships, which they could then take up or turn down.

**Comment by sanjayankur31** [comment]
Hrm. Sure. Let's do that. (I'm always happy to ask forgiveness later, but yeh that may be stickier than usual in this sort of thing).

So @OCNS/software-wg : please comment here (or on the doc) to indicate that you're happy with this submission by the end of the day. Otherwise we won't be able to add you to the author list this time.

**Comment by caglorithm** [comment]
Great! I'm going to put a "ok" after my name in the document!

**Comment by sras202** [comment]
Thanks Ankur for the document. I have added my affiliation and have done some minor corrections.

**Comment by mstimberg** [comment]
Hi everyone.  I don't have time to contribute atm, but happy with the content. Thanks for taking care of this!

**Comment by tnowotny** [comment]
Looks great, Ankur ... I am happy to be on it.

**Comment by jajcayn** [comment]
thanks for all the work on this! the document looks great

**Comment by kernfel** [comment]
What a brilliant mess of colours. It's almost a shame it has to be pruned to a single black-on-white submission, but I'm happy to be on it.

**Comment by sanjayankur31** [comment]
Thanks everyone. I've now accepted all the changes, so we're back to black and white pretty much.

@clinssen : your information was updated in the doc but from an anonymous account so I can't verify if it was you. Could you reply here once to confirm too when you have a minute please?

@adolocm : you're in the GitHub team: should I add your name in?

**Comment by clinssen** [comment]
Oops, yes, that was me. Many thanks!

**Comment by sanjayankur31** [comment]
> Oops, yes, that was me. Many thanks!

Thanks very much---I thought so, but felt it better to confirm :smile:

**Comment by appukuttan-shailesh** [comment]
We have now submitted the abstract. Closing this ticket.... (if and) when we get notified of acceptance, we will open a fresh ticket to discuss the poster. Cheers!

**Comment by appukuttan-shailesh** [comment]
Quick update... our abstract has been accepted:
> INCF is very happy to inform you that your abstract has been accepted to Neuroinformatics Assembly 2021!

We shall open a new ticket to discuss the poster in the coming days....

**Comment by adolocm** [comment]
Congrats!

**Comment by jimperlewitz** [comment]
Great!
