### ISSUE TITLE
Slides/Poster for INCF Assembly (due end of Friday 9th April)

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#19]
As conveyed earlier, INCF accepted our abstract about the Software WG. They now require us to submit a few slides describing our abstract. Their message:
> Upload max 5 slides describing your abstract to this google folder no later than Monday, April 12. Slides can be powerpoint, google slides, or pdf and should be in landscape layout (16:9 will look best).

**Deadline: Monday, April 12**

If I am not wrong, these slides are in lieu of the traditional poster - as appropriate for a virtual meeting.
I have made a workspace for us to collaborate here (Google Slides):
https://docs.google.com/presentation/d/1kjJk4JNwXf7M481MlLLNyucnMlEL9qnGLkVm8WSeFuE/edit?usp=sharing

I have dumped some general info there for now. It would be great if people could add content to it. For now lets not bother about the slide count, and we can eventually decide how to condense the material if required. The minutes of our first WG meeting might be a useful source of ideas to pick from:
https://ocns.github.io/SoftwareWG/2021/02/07/wg-meeting-26-january-2021.html

FYI, our abstract can be viewed here:
https://docs.google.com/document/d/1SLtnYvsn38p14uBHjtZSHR3B9DMnJQaBSsAUdOM-0T0/edit?usp=sharing

**Comment by appukuttan-shailesh** [comment]
(not sure if this needs explicit tagging to send out notifications: @OCNS/software-wg)

**Comment by sanjayankur31** [comment]
Thanks @appukuttan-shailesh . I've added the 5 slides now. Could everyone please suggest changes etc. by the end of tomorrow (Friday) so that we can submit these on Monday?

**Comment by malinINCF** [comment]
Excellent slides, I don't have much to add. Do we have any of the videos online yet? (we could link them in the last slide, if so)

**Comment by sanjayankur31** [comment]
Thanks for taking a look @malinINCF .

We have the zoom etc. upload links for the Dev sessions, but I've not had confirmation that the final branded versions have been uploaded yet.

**Comment by appukuttan-shailesh** [comment]
Thanks @sanjayankur31 for putting that together. I took a look at it now, and it seems appropriate for the stage that the WG is currently at. Did a bit of minor edits for now, but hoping to revisit this once again tomorrow.

**Comment by tnowotny** [comment]
looks good to me - nothing to add.

**Comment by kernfel** [comment]
Looks good! I've made a minor language edit on the final slide (till date -> to date), but couldn't find a way to track that change, other than through the version history. Not sure if I missed it or Slides simply doesn't do Track Changes...

**Comment by appukuttan-shailesh** [comment]
The slides have now been submitted. Thanks everyone for your inputs.
Hope to see many of you (virtually) at INCF :-)
