### ISSUE TITLE
Dev session: NeuroFedora

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#2]
I can do a session on [NeuroFedora](https://neuro.fedoraproject.org). We've got to pick a time etc.

**Comment by sanjayankur31** [comment]
I can do this on the 16th at 1700. BlueJeans will work for me too.

**Comment by brenthuisman** [comment]
I think I missed a meeting, but I'd be interested in attending this. And adding Arbor to its packages, maybe?

**Comment by sanjayankur31** [comment]
Sounds good. Arbor is already included in NeuroFedora: https://src.fedoraproject.org/rpms/arbor

(I think I need to double-check the flags that we use for building it, though. I remember some inconsistencies there.)

**Comment by brenthuisman** [comment]
Ah! A lot has changed since v0.3 though ;) I've no experience whatsoever with building rpms, but I could help you out with building if you like. I run Fedora (and use Neurofedora to have NEST), so maybe that helps. Let me know what I can do!

**Comment by sanjayankur31** [comment]
Sounds good. I've got a task for updating Arbor to the 0.5 release. I'll hopefully get down to it this week or the next.

That's great to hear! If you do have any suggestions/issues with NeuroFedora, please do let us know.

**Comment by sanjayankur31** [comment]
Web post is up: https://ocns.github.io/SoftwareWG/2021/02/07/dev-session-ankur-sinha-neurofedora.html

**Comment by sanjayankur31** [comment]
Announcements sent out to the various MLs.

**Comment by sanjayankur31** [comment]
The recordings are currently available [here](https://ucl.zoom.us/rec/share/d1-Ok50VwJp2a20AqUOKEnsXU-9iwdT2X-AnyLFSKeaLU-gYcXIQpvSazw9IJAIV.Hn0QHCUyofHZatPv). Code: `&=EcT%5o`. I'll pass them on to INCF Communications for uploading now.

**Comment by sanjayankur31** [comment]
E-mailed them the URL etc. now.

**Comment by sanjayankur31** [comment]
Post updated to include video: https://ocns.github.io/SoftwareWG/2021/02/07/dev-session-ankur-sinha-neurofedora.html 

Closing.
