### ISSUE TITLE
Make a common Software WG slide for use in software presentations

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#22]
From @clinssen 's suggestion here: https://github.com/OCNS/SoftwareWG/discussions/16#discussioncomment-686838

> Just a brainstorm idea: could we come up with a single slide, to share between all the tutorials/showcases, where we could advertise this OCNS WG and say a few words about research software engineering and its importance in neuroscience? Perhaps this could be a path towards onboarding new contributors (yes, we really do appreciate if you file a PR to fix that typo in the documentation)?

CC: @OCNS/software-wg: any takers? Should be a quick task?

**Comment by malinINCF** [comment]
I think this is a great idea, let's do it  :) I can do a slide for feedback if noone else volunteers. Google Slides?

**Comment by sanjayankur31** [comment]
> I think this is a great idea, let's do it :) I can do a slide for feedback if noone else volunteers. Google Slides?

That'll be great @malinINCF . Yes, Google slides works. We could even re-use some bits from the INCF slides perhaps? (You should have edit permissions to those too now).

Assigning to you. Updating milestone to CNS*2021 conf (since we don't need to have this done by the submission deadline).

**Comment by malinINCF** [comment]
Here is a first try - please tell me which more logos need to be fit in :)

[](https://docs.google.com/presentation/d/1jKwCWsuOCMnYFYc_gnnrA8YYKxLbxbi63oN9BO5anzU/edit#slide=id.p)

**Comment by mstimberg** [comment]
Logo-wise it looks good from my (i.e. Brian's) side. If you prefer a logo without background, please see: https://github.com/brian-team/brian-material/tree/master/logos

**Comment by clinssen** [comment]
> Here is a first try - please tell me which more logos need to be fit in :)
> 
> [Google slide](https://docs.google.com/presentation/d/1jKwCWsuOCMnYFYc_gnnrA8YYKxLbxbi63oN9BO5anzU/edit#slide=id.p)

NEST is missing! You can find some high-resolution logos here: https://github.com/nest/nest-simulator/tree/master/extras/logos Thanks in advance!

**Comment by malinINCF** [comment]
NEST is now added, thanks! Does anyone know if StdpC has any kind of logo/preferred illustration?

**Comment by tnowotny** [comment]
We never really made a logo ... @kernfel , any opinions on this?

**Comment by danieleavitabile** [comment]
Dear All, apologies for being latent. I have been a bit busy organising the International Conference on Mathematical Neuroscience, (ICMNS2021) which will be online, and will be announced soon. I thing there may be a chance to provide visibility for our group, and will keep you posted about it.

**Comment by kernfel** [comment]
Huh, yeah, I guess the one piece of software on the list that doesn't even exist without its GUI should probably have a logo. I'll see if I can't whip something up.

**Comment by clinssen** [comment]
> NEST is now added, thanks! Does anyone know if StdpC has any kind of logo/preferred illustration?

Many thanks, Malin!

**Comment by kernfel** [comment]
Thank you for the nudge, @malinINCF - StdpC now has a logo at https://github.com/CompEphys-team/stdpc/tree/development/logos

**Comment by malinINCF** [comment]
Excellent, added!

**Comment by sanjayankur31** [comment]
@malinINCF : I think this is now complete. Should we add it to the repo here as a resource for WG members?

**Comment by sanjayankur31** [comment]
I've uploaded the slide to our events repo in a folder called "general resources":

https://github.com/OCNS/SoftwareWG-events/tree/main/01_general_resources
