### ISSUE TITLE
Tutorial #1 at CNS*2021: bash

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#27]
Tracker ticket for the bash tutorial session at CNS*2021.

Current owners: @kernfel and ?

Initial curriculum (from the meeting, see #25 ):

- Command line:
  * Basics: Navigation, tab completion etc
  * Piping and redirection
  * Less, grep, etc.
- Things like not using spaces in file names
- SSH and SCP
- WSL?

**Comment by sanjayankur31** [comment]
@kernfel : all our tutorials were accepted. OCNS have said:

> 1) To attract CNS*2021 participants to your Tutorials, please prepare a detailed description of each of your tutorial in Word (or simple text) that we will be posting on the CNS*2021 Tutorials website. Please see this tutorial website for examples from previous years https://www.cnsorg.org/cns-2020-tutorials.
>
> The following items can be included:
> · (required) Description of the tutorial
> · Software tools
> · Tutorial content
> · Tutorial schedule (especially for full-day tutorial)
> · References and Background reading
> · Slides for participants to download and/or links to them
>
> Please email me this information by the latest of June 10th, 2021.
>
> 2) As you know already CNS*2021 is going to be an online event. The software tutorials are scheduled for June 28/29th.  We need to schedule the tutorials and to prepare the website for advertising them to our participants. For this, I need from you the following:
>
> a) Your order and preferred time for starting each tutorial by June 10^th, 2021. Please give me 2 times that show the time in EST/NY time (this is the official time for the CNS 2021 event) along with your local time. Please keep in mind that we might not be able to accommodate your desired times, but we will try our best. We will schedule some times that can accommodate most of the participants.
>
> b) Since participants can move between different tutorials, it would be good for you to prepare a schedule for each tutorial, in which you let participants know at what time a particular topic will be presented.  Half-day tutorials are 3h long. We suggest a break of 10-15 min after 90 minutes of tutorial time.
> 
> Full-day tutorials are 5-6h long. We suggest appropriate break times.

Could you please:

[ ] write up a short abstract of what you intend to cover in the session
[ ] list pre-requisites (what software folks should have installed etc.)
[ ] list references/reading for attendees

For the times, since we want the three sessions to be in sequence, given that the primary audience is probably US/EU based and the event timezone is EST, would the late morning/early afternoon in EU work for you? Something like 12 UTC on 28th? Which becomes ~2000 for you, and 0800 for US west coast?

![bash-tz](https://user-images.githubusercontent.com/102575/120615274-01b50380-c450-11eb-92c3-1b0df0ac61a4.png)

The git session can then be in the afternoon, and the python session the next day on the 29th.

No other tutorials will be happening in parallel with ours, so we don't need to worry about overlaps. (That's info that was sent out to all satellite tutorial organisers as part of the response template). The length of the session is up to you, with the maximum being 3 hours (including breaks).

If you can do these bits by the weekend, we'll send it across to Anca before the 10th as required.

@appukuttan-shailesh : anything I've missed?

**Comment by sanjayankur31** [comment]
I've created a repo for us here to store materials for our events. Please add any info here:

https://github.com/OCNS/SoftwareWG-events/tree/main/20210703-CNS2021/01_bash

**Comment by kernfel** [comment]
Yup, 12-15 UTC works for me. I'll provide the necessary details by Monday.

**Comment by kernfel** [comment]
I've added an abstract, prerequisites (I'm very grateful for WSL), and topics I intend to cover. I don't expect participants to prepare, other than getting their hands on a shell.

As for topics, I welcome any comments -- I'm trying to cover the very basics, so no scripting; if anyone feels I've missed something important or wants to contribute, please do let me know.

**Comment by mstimberg** [comment]
> I've added an abstract, prerequisites (I'm very grateful for WSL), and topics I intend to cover. I don't expect participants to prepare, other than getting their hands on a shell.

Just a comment on this (but I don't know much about Windows these days): for Software Carpentry we recommend the installation of "git for Windows" (https://gitforwindows.org), which unsurprisingly provides git (useful for the other tutorial), but also comes with the "git bash" command line, which should cover bash good enough for an introductory course. 

PS: Topics sound great to me, I'd maybe throw in the `sort` command as well.

**Comment by kernfel** [comment]
Good point, they'll want to have git ready anyway for the second tutorial. I've listed it as the preferred option.

As for `sort`: TIL!

**Comment by kernfel** [comment]
Thank you! I've added some of those explicitly (... now in a PR, I should probably join the git session). History things are included in the 'basics to refer back to'. `date` doesn't really fit anywhere, but I'll mention it; seems useful enough particularly these days.

**Comment by sanjayankur31** [comment]
Post is up, please do proofread and make any necessary modifications:

https://ocns.github.io/SoftwareWG/2021/06/09/software-wg-tutorials-at-cns-2021-online-bash-git-and-python.html

**Comment by kernfel** [comment]
Excellent, thank you!

**Comment by appukuttan-shailesh** [comment]
We should remember to send out info of these workshops on the mailing lists, and a reminder closer to the event.
We can probably close these three tickets (#27, #28, #29) now and open a new one to address publicity?

**Comment by sanjayankur31** [comment]
I'll close these once I've sent the doc to Anca. Just working on that now. Here's the link to the event time announcer (to be added to website once time is confirmed):

https://www.timeanddate.com/worldclock/fixedtime.html?msg=CNS%2A2021%3A+Effective+use+of+Bash&iso=20210628T08&p1=179&ah=3

**Comment by sanjayankur31** [comment]
Info sent to Anca.  Let's close this one. Please open new tickets with specific tasks if required.
