### ISSUE TITLE
Tutorial #2 at CNS*2021: git and GitHub

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#28]
Tracker ticket for the Git/GitHub tutorial at CNS*2021

Owners: @sanjayankur31 and ?

Initial ideas for curriculum (from meeting, see #25  ):

- Clone, add, branch, commit, open PR, go through “review” process to merge
- At end mention IDEs: Atom/GitHub desktop, yada yada
- Conflicts + merges

Additional ideas:

- rebasing (interactive)
- log/stash/worktree
- cherry-picking
- tags and releases

**Comment by sanjayankur31** [comment]
CC: @OCNS/software-wg

**Comment by sanjayankur31** [comment]
- bisect

**Comment by sanjayankur31** [comment]
All our tutorials were accepted. OCNS have said:

> 1) To attract CNS*2021 participants to your Tutorials, please prepare a detailed description of each of your tutorial in Word (or simple text) that we will be posting on the CNS*2021 Tutorials website. Please see this tutorial website for examples from previous years https://www.cnsorg.org/cns-2020-tutorials.
>
> The following items can be included:
> · (required) Description of the tutorial
> · Software tools
> · Tutorial content
> · Tutorial schedule (especially for full-day tutorial)
> · References and Background reading
> · Slides for participants to download and/or links to them
>
> Please email me this information by the latest of June 10th, 2021.
>
> 2) As you know already CNS*2021 is going to be an online event. The software tutorials are scheduled for June 28/29th.  We need to schedule the tutorials and to prepare the website for advertising them to our participants. For this, I need from you the following:
>
> a) Your order and preferred time for starting each tutorial by June 10^th, 2021. Please give me 2 times that show the time in EST/NY time (this is the official time for the CNS 2021 event) along with your local time. Please keep in mind that we might not be able to accommodate your desired times, but we will try our best. We will schedule some times that can accommodate most of the participants.
>
> b) Since participants can move between different tutorials, it would be good for you to prepare a schedule for each tutorial, in which you let participants know at what time a particular topic will be presented.  Half-day tutorials are 3h long. We suggest a break of 10-15 min after 90 minutes of tutorial time.
> 
> Full-day tutorials are 5-6h long. We suggest appropriate break times.


So, tasks:

[ ] write up short summary
[ ] write lists of pre-requisits
[ ] write lists of references

We want this session to be after the bash session, so we'll go for 1700 UTC.

The folder for materials for this session on the new events repo is here: https://github.com/OCNS/SoftwareWG-events/tree/main/20210703-CNS2021/02_git

**Comment by appukuttan-shailesh** [comment]
In different time zones (as for the bash post):
![image (2)](https://user-images.githubusercontent.com/24866517/120619830-a63d4280-c45c-11eb-9ec0-ae2d60007b44.png)

**Comment by tnowotny** [comment]
Sorry, getting a bit confused - which showcases are we covering here? I *think* our GeNN proposal was separate so isa a separate effort but I want to be sure. Would be nice to avoid a time clash also. Do I read it correct that the showcases covered here would be finished 18:30 UTC if starting 17:00?

**Comment by sanjayankur31** [comment]
Yes, the showcases are different. Showcases are scheduled for the first day of the main conference on the 3rd of July. The three software WG sessions are at the start of the week on Monday/Tuesday (28/29 June), followed by the satellite tutorials in the remaining of the week until July 3. There's a preliminary schedule up now:

https://www.cnsorg.org/cns-2021-tutorials

**Comment by sanjayankur31** [comment]
The 3 sessions that we're organising under the software WG are considered half day tutorials, so they can be up to 3 hours long. I doubt we'll use the full 3 hours, though.

**Comment by tnowotny** [comment]
oh - I see. Sorry for confusion.

**Comment by sanjayankur31** [comment]
Added the abstract here in a PR. Please do take a look:  https://github.com/OCNS/SoftwareWG-events/pull/1

**Comment by sanjayankur31** [comment]
Post is up, please do proofread and make any necessary modifications:

https://ocns.github.io/SoftwareWG/2021/06/09/software-wg-tutorials-at-cns-2021-online-bash-git-and-python.html

**Comment by sanjayankur31** [comment]
https://www.timeanddate.com/worldclock/fixedtime.html?msg=CNS%2A2021%3A+Effective+use+of+Git&iso=20210628T13&p1=179&ah=3

**Comment by sanjayankur31** [comment]
Info sent to Anca.  Let's close this one. Please open new tickets with specific tasks if required.
