### ISSUE TITLE
Feedback wanted on INCF blog post introducing the working group

### ISSUE THREAD

**Issue by malinINCF** [OCNS/SoftwareWG#30]
We will write blog posts for the INCF blog about our newest working groups, this working group is first out. I have a draft post that everyone is invited to comment on until Friday afternoon. It includes links to the dev session videos (just out this afternoon) and information about the tutorials at CNS*2021; other timely conent/inforamtion is welcome. You should have comment access if you follow this link

[Google doc draft](https://docs.google.com/document/d/1CbvafxhW7cGMCzzOqcL8Pf2AHI0PJ-774B7nvYPq6zc/edit?usp=sharing)

**Comment by sanjayankur31** [comment]
CC @OCNS/software-wg

**Comment by sanjayankur31** [comment]
Thanks very much for this @malinINCF . I've cc'd the team so that everyone gets notified and I've assigned the issue to you so you can close it when the task is complete.

**Comment by joewgraham** [comment]
It reads very well to me!  I made a few minor suggestions.

**Comment by mstimberg** [comment]
All looks good to me (including the comments by the others) :+1:

**Comment by tnowotny** [comment]
Do we also have the GeNN video?

**Comment by kernfel** [comment]
Looks good to me (besides the missing GeNN session).

**Comment by malinINCF** [comment]
The post is now published https://www.incf.org/blog/new-incf-working-group-incfocns-software-wg
