### ISSUE TITLE
Dev session: SciUnit

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#33]
Rick Gerkin (@rgerkin) has agreed to give a dev talk on [SciUnit](https://github.com/scidash/sciunit).
We shall finalize the date and time soon.

**Comment by appukuttan-shailesh** [comment]
Scheduling it for:
June 21 (Monday) at 18:00 CET

**Comment by sanjayankur31** [comment]
Announcements have now been sent out to neuroinfo, comp-neuro, and the system-neuro mailing lists. You can use the share buttons on the post to share this session on social media too:

https://ocns.github.io/SoftwareWG/2021/06/04/dev-session-rick-gerkin-sciunit.html

**Comment by appukuttan-shailesh** [comment]
Gentle reminder for the dev talk later today:

**Dev session: Rick Gerkin: SciUnit**
Date: June 21, 2021, 1600 UTC (Click [here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Dev+session%3A+Rick+Gerkin+%3A+SciUnit&iso=20210621T18&p1=195&ah=1) to see your local time).
Location (Zoom): https://ucl.zoom.us/j/91246735902?pwd=WVdVK3I5SGdlaDFZdllDQ0w2djVBdz09

(more details: https://ocns.github.io/SoftwareWG/2021/06/04/dev-session-rick-gerkin-sciunit.html)

Hope to see you there :-)

@@OCNS/software-wg, @rgerkin

**Comment by sanjayankur31** [comment]
Please retweet etc: 

https://twitter.com/sanjay_ankur/status/1406924950280314887

**Comment by sanjayankur31** [comment]
Hrm, recordings for this one are here. Sorry, I seem to have missed putting the link out:

https://ucl.zoom.us/rec/share/qG4D2ITH5wKVfBkHJwvHgBuBO32otP6gZKkEzUTw1UUkVr0erOY5agFrNhOhB_PC.xdFvTe_N3VLsJYZt

**Comment by sanjayankur31** [comment]
It's on the training space here also already, so closing:

https://training.incf.org/lesson/sciunit-demo
