### ISSUE TITLE
Change website theme

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#34]
The current theme works very well, but the formatting etc. isn't as clear as we'd like. For example, for long posts, there's far too much space between paragraphs and sections:

![website](https://user-images.githubusercontent.com/102575/121334858-f5c6b700-c911-11eb-9040-af2dcf5ec273.png)

So we'll find a different theme and update the website to use it.
All pelican themes can be found here:

http://pelicanthemes.com/

Any preferences @OCNS/software-wg ?

**Comment by mstimberg** [comment]
I agree that the section padding is excessive, but if this is the only thing that is wrong with the theme, it might be easier to simply add a [`custom.css`](https://github.com/textbook/bulrush/tree/master#custom-styling) with something like:
```css
.section {
    padding: 1rem 0.5rem;
}
```

**Comment by sanjayankur31** [comment]
I think the general text formatting is also not the best. It doesn't make too much difference in shorter posts but on longer pages/posts it somehow don't look quite neat enough to me.

For example: https://ocns.github.io/SoftwareWG/pages/about.html vs https://neuroblog.fedoraproject.org/2021/06/03/showcase-at-cns-2021.html

I'd like to avoid carrying css fixes/styling separate from the upstream theme since that increases the maintenance burden somewhat (and the less time we spend on figuring out css issues, the better XD)

**Comment by sanjayankur31** [comment]
![spacing-lists](https://user-images.githubusercontent.com/102575/121343382-83a6a000-c91a-11eb-9d99-bede50c68990.png)

Noticed that the list spacing when sub-lists are used also needs a little tweaking ^

**Comment by mstimberg** [comment]
I don't have strong opinions on this. I think having some minor CSS tweaks locally is fine (not sure that sending them upstream works, I think the original author put in the large section padding because they prefer it that way), but if there's another theme that works better out-of-the-box that would be preferable. I'm simply worried that other themes will have other things that need tweaking :)

**Comment by mstimberg** [comment]
> For example: https://ocns.github.io/SoftwareWG/pages/about.html vs https://neuroblog.fedoraproject.org/2021/06/03/showcase-at-cns-2021.html

I wouldn't mind the same theme as NeuroFedora (i.e. [pelican-alchemy](https://github.com/nairobilug/pelican-alchemy)), maybe customizing it with some [bootswatch theme](https://bootswatch.com/) to have it not look *exactly* the same :wink:

**Comment by sanjayankur31** [comment]
> > For example: https://ocns.github.io/SoftwareWG/pages/about.html vs https://neuroblog.fedoraproject.org/2021/06/03/showcase-at-cns-2021.html
> 
> I wouldn't mind the same theme as NeuroFedora (i.e. [pelican-alchemy](https://github.com/nairobilug/pelican-alchemy)), maybe customizing it with some [bootswatch theme](https://bootswatch.com/) to have it not look _exactly_ the same

That sounds like a great idea---pelican-achemy is quite a nice clean and modern theme. Let me create a new branch and tinker with that.
