### ISSUE TITLE
Dev session: GeNN

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#4]
We need to schedule a session on the development of GeNN.

**Comment by sanjayankur31** [comment]
@tnowotny : assigned to you, but please feel free to reassing/cc others.

We have Brian set up for 9th of Feb. Would the following weeks work for you?

**Comment by tnowotny** [comment]
How about week commencing 1 March? @neworderofjamie?

**Comment by neworderofjamie** [comment]
Sounds good to me

**Comment by sanjayankur31** [comment]
Thanks, that sounds great. Could you please choose a date/time so we can set up a meeting URL? What platform would you like to use? Would BlueJeans do or would you like to use another one (a university zoom service for example)?

If we can pick the time/date and set up a URL in the next few days, that'll allow us to announce this session later this week along with the Brian session. The Brian session is scheduled for the 9th, so I think we'd want the announcement to go out maybe by Thursday evening (4th) to give attendees enough of a heads up.

**Comment by tnowotny** [comment]
So, things have changed slightly and we would like to suggest 9 March. I think 17:00 GMT appears to work well. Does that seem ok for others?

**Comment by sanjayankur31** [comment]
That sounds good. If you can write up a short abstract, I'll get started on the website announcement etc. Could you also set up video meeting URL that will go into the announcements?

**Comment by neworderofjamie** [comment]
Topic: GeNN INCF SW SIG dev session
Time: Mar 9, 2021 05:00 PM London

Join Zoom Meeting
https://universityofsussex.zoom.us/j/97956408800?pwd=by9yVnhCZTJlenY0bVI4OEc5QWVFQT09

Meeting ID: 979 5640 8800
Passcode: 791336

**Comment by neworderofjamie** [comment]
Large-scale numerical simulations of brain circuit models are important for identifying hypotheses on brain functions and testing their consistency and plausibility. Similarly, spiking neural networks are also gaining traction in machine learning with the promise that neuromorphic hardware will eventually make them much more energy efficient than classical ANNs.
In this dev session, we will present the GeNN (GPU-enhanced Neuronal Networks) framework [1], which aims to facilitate the use of graphics accelerators for computational models of large-scale spiking neuronal networks to address the challenge of efficient simulations. GeNN is an open source library that generates code to accelerate the execution of network simulations on NVIDIA GPUs through a flexible and extensible interface, which does not require in-depth technical knowledge from the users. GeNN was originally developed as a pure C++ and CUDA library but, subsequently, we have added a Python interface and OpenCL backend. The Python interface has enabled us to develop a PyNN [2] frontend and we are also working on a Keras-inspired frontend for spike-based machine learning [3].

In the session we will briefly cover the history and basic philosophy of GeNN and show some simple examples of how it is used and how it works inside. We will then talk in more depth about its development with a focus on testing for GPU dependent software and some of the further developments such as Brian2GeNN [4].

[1] https://github.com/genn-team/genn 
[2] https://github.com/genn-team/pynn_genn
[3] https://github.com/genn-team/ml_genn
[4] https://github.com/brian-team/brian2genn

**Comment by sanjayankur31** [comment]
Post is up: https://ocns.github.io/SoftwareWG/2021/02/26/dev-session-james-knight-thomas-nowotny-genn.html

Please tweak it as necessary.

Do we have a logo or a featured image I can add? It just fits well with the social media platforms :D

**Comment by sanjayankur31** [comment]
I've sent the announcement out to the various mailing lists now. They should get through moderation and reach subscribers in some time. If there's anything else that needs to be done in the meantime, please do let me know.

Tweeted and tagged you folks too: https://twitter.com/sanjay_ankur/status/1367451269133176833?s=20

**Comment by neworderofjamie** [comment]
Glad you enjoyed it! Recording is at https://universityofsussex.zoom.us/rec/share/8rM8rffqsDpTwLc-ExBE9DXlr-7MPh4L3aSqYwWlMbYC0TkE_z5QVon6vC_MDHM.hJiPlUvskAlKGQSY

**Comment by sanjayankur31** [comment]
Video is here: https://www.youtube.com/watch?v=1ZHpKG41kp8

Post updated to include video: https://ocns.github.io/SoftwareWG/2021/02/26/dev-session-james-knight-thomas-nowotny-genn.html

Closing ticket now :)
