### ISSUE TITLE
Create zoom sessions for all tutorials

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#42]
We need to do these, but not advertise them. 

Does everyone have zoom accounts that allow for such long sessions? I can use my UCL account here.

**Comment by kernfel** [comment]
Yeah, I can do mine through UTokyo. How do we get the link to the participants?

**Comment by sanjayankur31** [comment]
I think the WOC are using Sched again this year, so the links will go there.

**Comment by kernfel** [comment]
In that case, here goes. https://u-tokyo-ac-jp.zoom.us/j/85094973076?pwd=Q1B3SEc2VWhVV2pIKzBvYmt6Yi9XUT09

**Comment by sanjayankur31** [comment]
let's collect them here but not advertise them (since folks are expected to register for the conf to attend any tutorials). I'll go ask the board if we can share the links with the OCNS membership at least, since we're an OCNS working group.

**Comment by sanjayankur31** [comment]
I've asked the Board:

- if we can open these sessions up to the public (i.e. not require registration)
- or if we can at least open them up to the INCF/OCNS membership (since we are an INCF/OCNS working group)

CC: @OCNS/software-wg

**Comment by sanjayankur31** [comment]
Git tutorial: https://ucl.zoom.us/j/94139686895?pwd=WFE3dVFtVElqdFFlS3Rtai9rNFlJUT09

```
Ankur Sinha (he/him/his) is inviting you to a scheduled Zoom meeting.

Topic: Software WG: Effective use of Git at CNS*2021
Time: Jun 28, 2021 06:00 PM London

Join Zoom Meeting
https://ucl.zoom.us/j/94139686895?pwd=WFE3dVFtVElqdFFlS3Rtai9rNFlJUT09

Meeting ID: 941 3968 6895
Passcode: 644379
One tap mobile
+13017158592,,94139686895#,,,,*644379# US (Washington DC)
+13126266799,,94139686895#,,,,*644379# US (Chicago)

Dial by your location
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
Meeting ID: 941 3968 6895
Passcode: 644379
Find your local number: https://ucl.zoom.us/u/achrmfNk98

```

Python tutorial: https://ucl.zoom.us/j/99188919533?pwd=bnB0dDdKMjBiR2dZUkRzbGFUcnIwdz09

```
Ankur Sinha (he/him/his) is inviting you to a scheduled Zoom meeting.

Topic: Software WG: Effective use of Python at CNS*2021
Time: Jun 29, 2021 02:00 PM London

Join Zoom Meeting
https://ucl.zoom.us/j/99188919533?pwd=bnB0dDdKMjBiR2dZUkRzbGFUcnIwdz09

Meeting ID: 991 8891 9533
Passcode: 427974
One tap mobile
+13017158592,,99188919533#,,,,*427974# US (Washington DC)
+13126266799,,99188919533#,,,,*427974# US (Chicago)

Dial by your location
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
Meeting ID: 991 8891 9533
Passcode: 427974
Find your local number: https://ucl.zoom.us/u/aqYNBiQYG
```

@appukuttan-shailesh , @joewgraham: please double-check the timings etc.

**Comment by appukuttan-shailesh** [comment]
Timings look fine :+1:

**Comment by sanjayankur31** [comment]
Closing this too---we're speaking to Anca about getting the links out since the conference Sched instance is unlikely to be ready for registrants before Monday.

**Comment by sanjayankur31** [comment]
@kernfel : could you let me know what e-mail you're using for the conf? I'll forward the sched info to you so you can tweak the session there (only presenters can do this).

**Comment by brenthuisman** [comment]
So, do I understand correctly OCNS won't be providing any conference infrastructure? They have not communicated this with me.

**Comment by sanjayankur31** [comment]
> So, do I understand correctly OCNS won't be providing any conference infrastructure? They have not communicated this with me.

Please speak to the tutorials chair etc about details. We have as much info as you  :)

**Comment by kernfel** [comment]
@sanjayankur31 Using <kernfel@ircn.jp> for OCNS/conference purposes.

**Comment by sanjayankur31** [comment]
Thanks, noted. Removing it from here now so that it doesn't get picked up by spammers!

**Comment by joewgraham** [comment]
> I've asked the Board:
> 
> * if we can open these sessions up to the public (i.e. not require registration)
> * or if we can at least open them up to the INCF/OCNS membership (since we are an INCF/OCNS working group)
> 
> CC: @OCNS/software-wg

Have you heard anything back from the board about opening the tutorials?  I've had a couple people ask...

**Comment by sanjayankur31** [comment]
No luck I'm afraid. Folks gotta register. We'll repeat the sessions
sometime and keep them open to the public then.
