### ISSUE TITLE
Publish recordings from CNS tutorials

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#43]
This ticket is for us to collect the URLs from the recordings, we'll pass them on to folks and INCF for permanent archival.
For the moment, I suggest folks be allowed to view the recordings but not download them.

Please feel free to share these links in the meantime @OCNS/software-wg .

**Comment by sanjayankur31** [comment]
Git session:

Recordings (currently on Zoom, will be archived on YouTube):  [LINK](https://ucl.zoom.us/rec/share/IIv4781-A1DJlh8gsBKSm9PXKdJ0cSXem3Uj7yCCVWw-XZKdvCsls7JPVQpOpbIz.4wCav4saSMc55Zct)
Notes: https://hackmd.io/@sanjayankur31/SkpuMdDh_

**Comment by kernfel** [comment]
Bash session: Archived (on YouTube)[https://www.youtube.com/watch?v=M8Qp38g4blU], with apologies for the missing bit after the break...

**Comment by sanjayankur31** [comment]
Here's the bit for the python tutorial:

[Link](https://ucl.zoom.us/rec/share/hWvcaOkH4D1MPhKnfKpVjfpXh_CBjmeRgYfEngqQF7g7lAIBSii-VqgkLZ85bPf3.yJwUM8wxhBEcfgM6)

@kernfel : please do keep the zoom recording too. As an INCF wg, our recordings can/should be uploaded to the INCF channels, so we'll contact them after the conference (similar to how the Dev sessions are uploaded to their channels).

**Comment by sanjayankur31** [comment]
Oh, and please remember to update the description of the topic on Sched to include the link. I'll also go update our blog post now.

**Comment by kernfel** [comment]
I somewhat stupidly recorded locally, but of course I'll keep that copy. It's around 200 MB, happy to send it to the right place.

**Comment by sanjayankur31** [comment]
Sure, no worries. We can upload it somewhere to share with INCF

**Comment by sanjayankur31** [comment]
These are all on Youtube now:

- bash: https://youtu.be/yQQC-6HnBtU
- python: https://youtu.be/Z4OohWlehH4
- git: https://youtu.be/CRCtRilX3NA

I'll update the post on the website now.

**Comment by sanjayankur31** [comment]
Also embedded in the web post now: 

https://ocns.github.io/SoftwareWG/2021/06/09/software-wg-tutorials-at-cns-2021-online-bash-git-and-python.html

**Comment by sanjayankur31** [comment]
Please signal boost: https://twitter.com/sanjay_ankur/status/1417153203964157961?s=20
