### ISSUE TITLE
Restarting meetings and dev sessions: when is everyone returning from holidays

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#46]
Hi @OCNS/software-wg : could everyone please comment to note when they're going away on the mid-term holidays, and when they'll be back available for meetings and dev sessions please? Especially parents who will have their hands full during the school holidays?

The idea is to restart meetings and dev sessions after the mid-term break, perhaps at the end of August/starting of September. If everyone can note when they'll be ready for these, we can start pencilling in dates.

Thanks very much,

**Comment by appukuttan-shailesh** [comment]
I will be away from July 21 to 27, and then possibly around end-August to mid-September.... (highly dependent on how Covid situation in the coming months!). But I should be able to attend short sessions/events during the latter period.

**Comment by kernfel** [comment]
I'll be away July 22-25 as well as September 16-24. I'll probably have my laptop with me in September and may be able to attend.

**Comment by jimperlewitz** [comment]
Not an issue for me.

**Comment by mstimberg** [comment]
Hi everyone, I won't be available pretty much all the summer. Will be back in office September 6th.

**Comment by sanjayankur31** [comment]
I'll be away next week, but then should be at work throughout other than a few days here and there where I may take leave.

**Comment by brenthuisman** [comment]
I leave next week, then spend nearly all of august in a course. I guess september will be the first month most of us are going to be back.

**Comment by juhuntenburg** [comment]
Hi, I'm new (see intro in discussions) and would be curious to join the next meeting after the break. I will be away August 9-27

**Comment by tnowotny** [comment]
Everything is up in the air with the covid situation but it is fair to say I will probably be either away or busy with family during the school vacations 26 July - 5 September.

**Comment by stewart-heitmann** [comment]
Hi all,

I find that these meetings tend to be scheduled in the dead of night in my time zone (Sydney, Australia). Am I the only one who has this problem or are others effected too? I am just curious.

Obviously there will always be winners and losers. Australia often loses to America and Europe (for good reason) because they have the majority of delegates.

Stewart Heitmann (Brain Dynamics Toolbox)

**Comment by kernfel** [comment]
Hi Stewart,
I'm in the same boat (Tokyo). With the critical mass of this group centered around Europe, I think it's only fair that the meeting times swing around from Europe/Americas to Europe/Asia/Pacific, as they have done. Some clashing is unavoidable given our distribution across the planet.

**Comment by stewart-heitmann** [comment]
OK. Thanks Felix. That’s good to know. It seems that we are the only two.

Stewart 

PS: I hope your Bash tutorial went well.

**Comment by joewgraham** [comment]
I am on vacation now, but will be back and available in a week or so, and should be available the rest of the summer.

**Comment by sanjayankur31** [comment]
Let's wait for everyone to return. So, we can start planning bits for end of September or the start of October. I'll write a short blog post noting that we're all on vacation and will return then.

**Comment by sanjayankur31** [comment]
https://ocns.github.io/SoftwareWG/2021/07/19/summer-vacations.html
