### ISSUE TITLE
Dev session: neurolib

### ISSUE THREAD

**Issue by caglorithm** [OCNS/SoftwareWG#5]
I'm proactively adding an issue for scheduling time/date for the session on neurolib.

**Comment by sanjayankur31** [comment]
Thanks @caglorithm . Assigning to you too.

**Comment by sanjayankur31** [comment]
We have Brian set up for 9th of Feb. Would the following weeks work for you?

**Comment by sanjayankur31** [comment]
NeuroFedora is set up for the week after (16th Feb), and GeNN is set up for the first week of March. Would the third week of Feb, starting on 22nd Feb work for you @caglorithm ?

**Comment by caglorithm** [comment]
Thanks for setting up everything @sanjayankur31. Could you maybe tell me a bit about the format of the sessions? I couldn't participate in the meeting so I don't really know anything apart from the log that I've read. What's the primary goal of the session? Will it be tutorial-like? Did you already agree on know how long each session will be?

**Comment by sanjayankur31** [comment]
The goal of the sessions is to share knowledge of how research tools are developed

So, these sessions are intended to discuss the development side of the project. Most of us intend to give a short demonstration of how the tool is to be used with, to start with---to show what it does and how etc. A short overview. Then we intend to move on to the development side of things---how the tool is developed, what the pipeline is, what the contributing guidelines are and so on. If there are some easy issues for beginners to work on, that'll be an added bonus, since it'll help the project get some new contributors.

We expect the sessions to be 1 hour long, but we haven't set an explicit limit.

**Comment by caglorithm** [comment]
@sanjayankur31, 22nd February is good for me. Looking forward!

**Comment by sanjayankur31** [comment]
Sounds good. What time would you prefer? Does 1700 UTC work?

**Comment by sanjayankur31** [comment]
Oh, also: could you give me a short abstract/summary for the talk to put up on the website etc.? (Like [here](https://ocns.github.io/SoftwareWG/2021/02/07/dev-session-marcel-stimberg-brian-simulator.html))

**Comment by caglorithm** [comment]
Yes, 1700 UTC works for me!

**Comment by caglorithm** [comment]
Sure, here you go:

neurolib is a computational framework for whole-brain modeling written in Python. It provides a set of neural mass models that represent the average activity of a brain region on a mesoscopic scale. In a whole-brain network model, brain regions are connected with each other based on structural connectivity data, i.e. the connectome of the brain. neurolib can load structural and functional data sets, set up a whole-brain model, manage its parameters, simulate it, and organize its outputs for later analysis. The activity of each brain region can be converted into a simulated BOLD signal in order to calibrate the model to empirical data from functional magnetic resonance imaging (fMRI). Extensive model analysis is possible using a parameter exploration module, which allows to characterize the model's behavior given a set of changing parameters. An optimization module allows for fitting a model to multimodal empirical data using an evolutionary algorithm. Besides its included functionality, neurolib is designed to be extendable such that custom neural mass models can be implemented easily. neurolib offers a versatile platform for computational neuroscientists for prototyping models, managing large numerical experiments, studying the structure-function relationship of brain networks, and for in-silico optimization of whole-brain models.

**Comment by sanjayankur31** [comment]
Thanks, I'll set it up on the website and ping you there before sending the announcement out.

One last thing: are there any accounts I can tag when I post the announcement on twitter etc? Either for the software or for you/the dev team?

**Comment by caglorithm** [comment]
Sure, my twitter handle is @caglorithm, the account of @neurolib-dev is still in its infancy, almost nothing happening there yet. Maybe you can just use both?

I have created a Zoom meeting, in case you would like to use it.

```
Topic: OCNS Dev sessions: neurolib
Time: Feb 22, 2021 18:00 Berlin / 17:00 UTC

Join Zoom Meeting
https://tu-berlin.zoom.us/j/68960683644?pwd=a2JTTS8xZXhwY0ZtQ0J0aktRVW52Zz09
```

**Comment by sanjayankur31** [comment]
Thanks, I'll use this!

**Comment by sanjayankur31** [comment]
I've put the post up now @caglorithm : https://ocns.github.io/SoftwareWG/2021/02/12/dev-session-caglar-cakan-neurolib.html

Could you take a look to see if everything there is OK?
Also, for the Zoom call, are the security settings set correctly so that anyone with a Zoom account can join? (Here at UCL, the default was set to only allow other UCL Zoom accounts to join).

**Comment by caglorithm** [comment]
Perfect, thanks!

Users should be able to join the Zoom call without an account, according to the privacy regulations of the TU Berlin.

**Comment by sanjayankur31** [comment]
Sounds good. I'll send out the announcement to the MLs tomorrow morning.

**Comment by caglorithm** [comment]
Hi @sanjayankur31, did you send out the invitation yet? I noticed that, the last 2 times, we met on Tuesday. Feb 22nd is a Monday, are you aware of that? Might be better to stay on the same week day, but I can do both! Please let me know what you think is better.

**Comment by sanjayankur31** [comment]
No, I'm sending the mails out now.

Yeh, I knew it was Monday but as long as we'd announced it in advance I didn't think it'd make a difference---the sessions will be held whenever convenient for the speaker. 

If you want we can move to the Tuesday: can you create a new zoom meeting and share the link? I'll update the website announcement etc. too.

**Comment by sanjayankur31** [comment]
@caglorithm : double-checking: would the zoom link stay the same if we move to Tuesday, or would you have to create a new one?

**Comment by caglorithm** [comment]
@sanjayankur31 sorry for the delay, I had problems receiving mail notificaitons. I changed the date, the URL stayed the same!

```
Caglar Cakan is inviting you to a scheduled Zoom meeting on the TU Berlin zoom service.

Topic: OCNS Dev sessions: neurolib
Time: Feb 23, 2021 06:00 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://tu-berlin.zoom.us/j/68960683644?pwd=a2JTTS8xZXhwY0ZtQ0J0aktRVW52Zz09

```

**Comment by sanjayankur31** [comment]
Thanks! I'll send it out first thing tomorrow morning.

-- 
Thanks,

Ankur

(Sent from mobile device)

**Comment by sanjayankur31** [comment]
Announcement sent to mailing lists. Twitter announcement sent: https://twitter.com/sanjay_ankur/status/1362344544357011456?s=20

**Comment by sanjayankur31** [comment]
Recordings are here now. Got to update the website post: 

https://www.youtube.com/watch?v=ngvVtqiilVk

**Comment by sanjayankur31** [comment]
Post updated to include video: https://ocns.github.io/SoftwareWG/2021/02/12/dev-session-caglar-cakan-neurolib.html

Closing.
