### ISSUE TITLE
Regular monthly meeting alternating between American and Asian time zones?

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#54]
Hi @OCNS/software-wg 

I was wondering what folks thought of having a regular meeting time set up for each month so we can block it off in our calendars early?
At the moment we do a whenisgood each time, but that takes time and availability often changes while it's being populated by everyone.

So I propose that 

- we set up a regular meeting time for a one hour meeting every month
- this time alternates between a time friendly for the American time zone, and a time friendly for the Asian time zones.

So, starting from January, how is the second Monday each month at:

- 1700 UTC
- 0800 UTC

What do you think?

**Comment by appukuttan-shailesh** [comment]
Both these time slots work for me :+1:

**Comment by stewart-heitmann** [comment]
Perfect with me!

Stewart Heitmann
***@***.***

**Comment by malinINCF** [comment]
Both times work for me.

**Comment by tnowotny** [comment]
the 8am might not work for me (school run) but not necessarily a reason to not do it ...

**Comment by sanjayankur31** [comment]
Yeh, I think some of us will be able to make one and not the other sometimes, but as long as there are a few of us who overlap to keep the alternating meetings connected in a way, we should be fine.

(Just to be clear: I'm suggesting that in Jan we do 0800 UTC, then in Feb we do 1700 UTC, March 0900 UTC and so on---so most of us should at least be able to attend one meeting that suits them)

**Comment by jimperlewitz** [comment]
That works.

**Comment by kernfel** [comment]
Excellent suggestion. I'll be there half the time!

**Comment by sanjayankur31** [comment]
Great, I'll leave this open for a few more days for others to chime in, and then I can set up a recurring meeting reminder for us somewhere. :+1:

**Comment by sanjayankur31** [comment]
OK, since we haven't received any other feedback, this is now good to go. We will meet on the second monday each month, and the time will alternate between 1700 UTC and 0800 UTC. 

I'll update our blog etc., and open a new ticket for the January meeting.
