### ISSUE TITLE
Next meeting: Monday 10 January 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#56]
The next meeting is on Monday 10 January 1t 1700 UTC.

@OCNS/software-wg: Please comment on this ticket to add items to the agenda.

Logs from the last meeting on October 21 are here: https://ocns.github.io/SoftwareWG/2021/10/28/wg-meeting-21-october-2021.html

**Comment by appukuttan-shailesh** [comment]
Some items to discuss:
- how we can improve participation for our events
- apart from our regular dev talks, what other events to plan this coming year

**Comment by sanjayankur31** [comment]
- Notes/comments/discussion on the software citation principles dev session

- preparation for CNS*2021
  - call for tutorials/workshops usually goes out in January
  - repeat of satellite tutorials like last year would perhaps be a good starting point
    - Command line 101
    - Python 101
    - Git 101
    - Containers 101?
    - ..?

- making the working group more diverse

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg : reminder for today's meeting at 1700 UTC. We hope to see you there.

**Comment by sanjayankur31** [comment]
I've started the call now folks, please join at your convenience.

**Comment by sanjayankur31** [comment]
Thanks for attending the meeting everyone, the minutes are here:

https://hackmd.io/s/SkxhEkchF

I'll publish them on the website next week, so please feel free to add more notes and so on.
For those that weren't able to attend the meeting, please do go through the logs and drop your views either on the notes or here in this ticket.
