### ISSUE TITLE
Next WG meeting: March 14 2022 at 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#60]
@OCNS/software-wg : the next meeting is on March 14 at 1700 UTC. Please use this ticket to add any items to the agenda.

Logs from the January meeting are here: https://ocns.github.io/SoftwareWG/2022/03/02/wg-meeting-14-february-2022.html

Initial agenda items

- update on tutorial survey form (https://github.com/OCNS/SoftwareWG/issues/57)
- CNS 2022 tutorial preparation (based on results from survey, and general ideas)

Please do try to attend the meeting, or add any comments/topics here so they can be brought up.

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg ,

Hope you are all well

A reminder of Monday's meeting at 1700 UTC. Please do try to attend it, and if you are unable to, please comment on the agenda items here in this ticket.

We'll use jitsi again. Here's the link: https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg : reminder for today's meeting at 1700 UTC. 

Please add any items to the agenda, or drop comments if you're unable to make it to the meeting please.

Jitsi link:

**Comment by mstimberg** [comment]
Hi everyone :wave: Unfortunately I cannot join you today (again), but I'll go through the meeting notes later. Also, happy to be involved in satellite tutorials, assuming they will take place online.

**Comment by appukuttan-shailesh** [comment]
Sorry, I was out (currently in India on holidays, so that's my excuse ;-) and couldn't make it back in time.
I joined the session just now, but it seems we have already wrapped up?

**Comment by sanjayankur31** [comment]
Yeh, it was @malinINCF and me so we went over the agenda. Couldn't make any decisions on the tutorials etc., so we'll have to do that via tickets.

The minutes doc is here:

https://hackmd.io/s/ByC18l6W5

Folks, please add any notes there. Cheers.

**Comment by sanjayankur31** [comment]
I'll publish these on the website on Monday @OCNS/software-wg . Please make your edits/additions before then.
