### ISSUE TITLE
Next WG meeting: April 11 2022 at 0800 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#65]
@OCNS/software-wg  : the next meeting is on April 11 at 0800 UTC. Please block your calendars so you can attend the meeting. Please use this ticket to add any items to the agenda.

Logs from the previous meeting are here: https://ocns.github.io/SoftwareWG/2022/04/01/wg-meeting-14-march-2022.html

If you are unable to attend the meeting, please drop your comments on the ticket here and let us know.

**Comment by appukuttan-shailesh** [comment]
Some agenda items
- discuss outcome of our survey
- plan for tutorials as part of CNS 2022: _decide topics, tutors, ..._
- ideas for increasing our reach and membership
- creating a WG mailing list

**Comment by sanjayankur31** [comment]
+1, I had these notes made, so just fleshing out what you've noted @appukuttan-shailesh : 

### CNS 2022 tutorials

- go over survey results 
- decide on satellite tutorial sessions (we are confirming them with the OCNS organising committee now, and should have confirmation soon)
  - WG members are invited to hold tutorial sessions for their respective tools
  - we will reach out to non WG members to invite them to organise sessions for their tools

###  Diversity & inclusion session at incf assembly

- birds of a feather "bof" session has been accepted
- we need input on what sessions to organise and who to invite
- we need input on what the goals (deliverables) of this session should be

#### Software arena session at incf assembly

- has also been accepted
- input on the best way of doing this, and what our expected goals are

### WG business

- we don't currently have a way of actively communicating with the WG membership because we don't have a mailing list sort of thing where any announcements go straight to the members' inboxes (we don't even have all your e-mails because we decided not to use mailing lists when we started). 
- the worry, however, is that using GitHub tickets/discussions is passive---i.e., folks do get notifications, but they still need to come up to the repository to engage
- the lack of something like a mailing list also means that we don't have a way of actively informing the community (outside our membership) of our activities

So:

- do we need a better way of keeping the wg membership in the loop? are you satisfied with our current way of doing things?
- are fixed meeting slots working? (we've had a lower than usual turnout recently---what can we do to help more of our members attend meetings?)

For communicating with the research community:

- should we send more updates to the already existing mailing lists (for example, should a note of our meeting be sent there?)
- or do we need a new mailing list/newsletter setup that folks can subscribe to? (in case our frequent posts to already existing mailing lists are thought to be an abuse of their policies?)


#### Increasing our membership

- what steps can we take to encourage more folks to join the WG?
- are their incentives we can think of to encourage students to join us for example? Simpler tasks for them to do, for example? (see #63 for example)

#### "Easyfix"

- thoughts on #63

... add your agenda item here ...

**Comment by sanjayankur31** [comment]
This came up briefly during the NetPyNE dev session:

- Possibility of standardising simulation generated output data (or facilitating conversion to NWB type formats to take advantage of the software/analysis eco system)

The general idea is that if we can agree on a standard format for simulator generated data, we can all use/re-use the same libraries/plotting utilities instead of each simulator community having its own packages. Ideally, simulation data should be closely linked to experimental data to make comparison/validation etc. as seamless as possible.

I've heard that this has been discussed before, quite a while back, and things like SONATA were involved. If folks have info on this, please share it here so that we newcomers can get up to date :)

**Comment by malinINCF** [comment]
Hi, I will miss most or all of this meeting since it collides with an INCF staff meeting that starts at the same time. If my other meeting runs short, I will try to join you.

**Comment by sanjayankur31** [comment]
Thanks Malin.

Everyone else @OCNS/software-wg , the meeting starts in about an hour. Please do join us. Here's the jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

See you all in a bit :)

**Comment by sanjayankur31** [comment]
hi @OCNS/software-wg , thanks for coming to the meeting. We discussed quite a few issues. Please see the minutes here and add your comments/thoughts:

https://hackmd.io/@sanjayankur31/SJMqxwZVc

I'll publish the minutes on the website next week sometime.

**Comment by joewgraham** [comment]
I had my alarm set, but somehow managed to turn it off in my sleep.  Sorry I missed the meeting!

I think the satellite tutorials were a success last time, and I'm willing to lead one on virtual environments or Python.

I think having an actual mailing list would be good for a lot of announcements, how does one join the list?

In terms of meeting schedules, I do find that 4am is a bit tough!

**Comment by sanjayankur31** [comment]
> I had my alarm set, but somehow managed to turn it off in my sleep. Sorry I missed the meeting!
> 
> I think the satellite tutorials were a success last time, and I'm willing to lead one on virtual environments or Python.

Thanks. I think we need to take a look at the survey results to see what sessions to host, but a beginner level python session is always useful IMO.

> 
> I think having an actual mailing list would be good for a lot of announcements, how does one join the list?

We need to set one up now, and then we'll be able to advertise it/add people to it.

> > In terms of meeting schedules, I do find that 4am is a bit tough!
> 
> Speaking as one of the reasons the meetings ping-pong to an Asian-fitting schedule, I'd be okay with moving it westward by 2 hours if that helps more people join. On the other hand, I think @stewart-heitmann might disapprove, since he's 2 hours to the east of myself.


I'd like to keep the two different times to ensure that we remain accessible to all time zones. Otherwise someone will always miss out---even if we do whenisgood/doodle polls.

Instead of alternating, I'm happy to host two meetings each month---one for each time zone? So that way we'll have a wg meeting at both 0800 and 1700 UTC and folks can attend whichever suits them. Would that help?

**Comment by stewart-heitmann** [comment]
Hi all,

Yes I would prefer a mailing list over github notifications. Good idea.

I have just submitted a proposal for a Software Showcase for the Brain Dynamics Toolbox at CNS*2022. In my case, a showcase is more appropriate than a tutorial because I already have online training courses. Outreach is my goal.

Stewart Heitmann
***@***.***

**Comment by sanjayankur31** [comment]
Thanks.

I just want to note that the plan is not to replace GitHub
issues/discussions with the mailing list. The list will be mostly for
announcements (because we currently dont have a channel for such
communication). Our discussions will continue here on GitHub as we do now.

-- 
Thanks,

Ankur

(Sent from mobile device)

**Comment by sanjayankur31** [comment]
The minutes have not been published here:

https://ocns.github.io/SoftwareWG/2022/04/21/wg-meeting-11-april-2022.html

Please go through them if you haven't had a chance yet, and open new tickets wherever required.
