### ISSUE TITLE
CNS*2022 satellite tutorials: list of tutorials to try and organise (either us or by inviting devs)

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#68]
A list of topics that will be part of the Satellite tutorials.

@OCNS/software-wg would someone want to go over the survey results and come up with a list?

Once we have a list, we need to see which topics we (the WG) can organise, and who we'll need to invite to cover other topics. 
Additionally, we can also send out an open call to the mailing lists requesting folks to get in touch with us if they'd like to organise a tutorial about their software as part of this.

**Comment by appukuttan-shailesh** [comment]
During the last meetings/dev sessions we had talks about interoperability and file formats, and the topic of Neo and NWB came up. I spoke informally to Andrew Davison this morning whether he/others would be interested in conducting a tutorial session on using Neo (and also its integration with NWB) - from a beginners perspective. He felt it was a good idea, and might be up for putting together a tutorial. So this is one propsective tutorial we can consider.

**Comment by sanjayankur31** [comment]
Cool, I was also planning to reach out to the NeuralEnsemble folks to see if they wanted to do sessions on elephant etc. 

How do we want to do this? Ticket tracking each tutorial session? (If Neo/NWB is sort of confirmed, for example, do we open a ticket for it to track its progress?)

**Comment by appukuttan-shailesh** [comment]
I think so... we can have one per proposed tutorial. Easier to track individual progress.
I shall create one for **Neo** after I have a more detailed talk with Andrew next week.

**Comment by sanjayankur31** [comment]
Shailesh and I have added tickets inviting members of the WG to host satellite tutorials on their tools, and a few others that we know about for a start. Please see:

- #80 
- #79 
- #78 
- #77 
- #76 
- #75 
- #74 
- #73

**Comment by sanjayankur31** [comment]
Please reach out to developer teams of any tools you'd like to see satellite tutorials for (or note them here and we can reach out to them). 

What do folks think of also sending out a general invitation to the mailing lists?

**Comment by appukuttan-shailesh** [comment]
It seems to me that we might easily have 3-5 confirmed tutorials from the above list.
I am a bit wary of sending out an invite on the mailing lists, considering that we could potentially get several expression of interests - and not sure how many we can actually manage to fit in.

Can we decide on an approximate number... just to have an idea.

We could have two formats:
- short tutorial : 1 - 1.5 hours
- regular tutorials : ~3 hours.

We have 5 working days (June 27 - July 1).
I would think not more than 5-6 hours of tutorials per day.

**Comment by sanjayankur31** [comment]
There are two ways of doing this:

- a select set of tutorials: this is the "traditional way"---similar to workshops at CNS. Someone (in this case, we?) invite select people to hold some sessions.
- lots of tutorials, for all tool developers that want to host them---allowing users to attend whatever tools they want to learn, and all of these get recorded for later viewing/study on somewhere like the INCF training space

I'm not a fan of the first way---because that limits tutorials to tools that we (or someone) decide to be "important". That automatically means that these will again lean towards the "most popular tools in the field", which don't really need more visibility tbh. So, I tend to lean towards a more community based approach---the second one---where whoever wants to host a tutorial about their tool is welcome to do so. That way we don't decide what tutorials are to be hosted---the developers of these tools do. Our task becomes to enable them by doing the organisation bits to provide a platform (website, registration, advertising, zoom links, someplace to upload recordings etc.). 

If we get the word out well enough, we'll (should) have lots of folks attending---we had hundreds (or was it about 2k?) at the free online CNS conferences IIRC.

Having said all of this, I do understand that we will need some limits, but we're not limited by any particular time zone (folks can even do two sessions if they want---in different time zones), so we can theoretically spread the tutorials over a full 24 hour period.

What do folks think?

PS: I've also just posted the current results of the survey in #82: lots of tools there that people would like to learn
