### ISSUE TITLE
Set up new announcement only mailing list for the WG

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#70]
We agreed to set up an announcement only mailing  list for the WG at the last @OCNS/software-wg  meeting.  (Discussions will remain here on GitHub.)

Suggestion: softwarewg@lists.incf.org (using the INCF mailman instance, whatever it's URL is)

Initial admins/moderators: @sanjayankur31 @appukuttan-shailesh @kernfel @malinINCF  (to be set once list is setup and these folks have subscribed).

If anyone else would like to help moderate the list, please let us know here too.

**Comment by malinINCF** [comment]
The mailing list setup is in progress. The address will be incf-ocns-software-wg@incf.org (slightly clunkier but also more identifiable). The moderators have been added.

Register at: [https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg](https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg)

**Comment by sanjayankur31** [comment]
Awesome, thanks very much @malinINCF !

I'll update the website.

PS: I'm going to use my gmail address for this so that it's permanent and I can set up filters etc. there

**Comment by sanjayankur31** [comment]
Hrm, works for me now. Can you try again? I think the INCF infra folks were updating the server at some point. You may have managed to get caught in the outage.

**Comment by sanjayankur31** [comment]
I'm still getting bounces when I try to e-mail the list, so I'll probably try tomorrow to make sure the outage is over. If it still errors, we'll have to contact the incf admins to check what's up.

**Comment by malinINCF** [comment]
Our admin told me the whole server went down after the update, so it may take a while.
