### ISSUE TITLE
CNS*2022 satellite tutorial: Brian2

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#74]
@mstimberg : it'll be great to host a satellite tutorial on Brian. What do you think?

**Comment by mstimberg** [comment]
Would be happy to host one of course, but I'll need to figure out whether/when I'll be available for the available dates.

**Comment by sanjayankur31** [comment]
Sounds good. Thanks very much.

**Comment by mstimberg** [comment]
Just to dump some basic info here: still happy to do the tutorial. Not 100% sure about the final format and who will be doing it (if only me or someone else as well). Would go for the half-day size. No clear preference for the day until now, but would strongly prefer some European time slot, say ideally something in the 10h-18h CEST time frame. Can set up my own Zoom and website.

**Comment by mstimberg** [comment]
Just to complete: all days can work in principle, but I'd like to avoid Wednesday (29th) if possible. Tuesday or Thursday would be ideal. We don't have a website yet, but we will set one up beginning of June.

**Comment by tnowotny** [comment]
@sanjayankur31 , what is the time zone for the timings on the schedule you put on the website (BST?) - maybe worth mentioning there

**Comment by sanjayankur31** [comment]
It's all UTC there, I'll double check that I've mentioned it, and I'll see if I can link to a timezone converter thing later.

**Comment by sanjayankur31** [comment]
I'll post regular updates on number of registrations and who intends to attend what so all tutors can prepare accordingly on this ticket here---please keep an eye on it: #106
