### ISSUE TITLE
CNS*2022 satellite tutorial: Neo + Elephant

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#75]
Andrew Davison and co are considering a tutorial on Neo (and possibly also its integration with NWB).
Will be discussing with him this week. Shall update this ticket once I have more info.

**Comment by appukuttan-shailesh** [comment]
Andrew Davison (@apdavison) and Michael Denker (@mdenker) have discussed and intend to do a combined tutorial session for Elephant & Neo. Probably a half-day session: ~3 hours.

In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

**Comment by mdenker** [comment]
Hi @sanjayankur31, thanks, for me that would work very well!

**Comment by apdavison** [comment]
works for me also

**Comment by sanjayankur31** [comment]
Thanks @mdenker @apdavison . I've marked your session as confirmed in the spreadsheet now.

**Comment by sanjayankur31** [comment]
Hi @mdenker @apdavison , I've published the schedule on our website [here](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html), and we'll publish the Zoom links in a different document whose link we'll send out in the registration confirmation e-mail.

Could you please set up a zoom meeting and a web page (optional) and send me the links privately via e-mail at ankursinha AT fedoraproject DOT org when you have some time to spare please? If you don't have institutional access to a zoom like platform, I can also set a zoom meeting up for you, please let me know.
