### ISSUE TITLE
CNS*2022 satellite tutorial: GeNN

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#76]
@tnowotny @neworderofjamie: it'll be great to have a satellite tutorial on GeNN---what do you think?

**Comment by tnowotny** [comment]
We have proposed a "proper" tutorial on GeNN on site. Not sure whether that is a reason to or not to run a satellite.

**Comment by sanjayankur31** [comment]
Thanks, that sounds good. I don't see an issue with tutorials at both myself---given that the "proper" tutorials would be limited to people that can make it to Melbourne only. We can leave this open to decide at a later date---depending on what you all (the devs) and what others in the WG think about it.

**Comment by tnowotny** [comment]
Agreed, as we are preparing the material anyway, holding it online as a satellite would only involve the time spent to actually hold it. So could be good value for money for us @neworderofjamie

**Comment by appukuttan-shailesh** [comment]
@tnowotny : Do you think we should run it past the OCNS board to confirm there is no potential conflict in having the same sessions being offered via the free online software tutorials and the paid on-site tutorials? We seem to have a few such cases. (There is naturally a difference between online vs on-site, but wondering if it is better to inform and take approval beforehand).

**Comment by tnowotny** [comment]
I would think it would be a nice gesture to ask them - though I don't think there is a problem.

**Comment by sanjayankur31** [comment]
Hi @tnowotny @neworderofjamie

In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

**Comment by tnowotny** [comment]
Ok, sorry for the delay. Here is my/our take:
- what is the expected duration of the session?
3 hours

- what is the preferred start time of the session (in UTC)?
no strong preference, but best between 10:00 and 17:00.

- are there days that you cannot hold the session in the June 27--July 1 interval?
27 June preferred (then both @tnowotny  and @neworderofjamie can lead), otherwise any day with @tnowotny as lead.

- would you like us to set up zoom meeting rooms for you (for organisers
that may not have access to institutional zoom etc. subscriptions)?
We have our own institutional zoom subscription and will set up ourselves.

**Comment by sanjayankur31** [comment]
Thanks very much. We'll have a draft schedule up as soon as we have everyone's responses.

**Comment by sanjayankur31** [comment]
Hi @tnowotny @neworderofjamie , I've published the schedule on our website [here](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html), and we'll publish the Zoom links in a different document whose link we'll send out in the registration confirmation e-mail.

Could you please set up a zoom meeting and a web page (optional) and send me the links via e-mail at `ankursinha AT fedoraproject DOT org` when you have some time to spare please?

**Comment by tnowotny** [comment]
@sanjayankur31 , the link for further information for this tutorial will be https://genn-team.github.io/tutorials.html

**Comment by neworderofjamie** [comment]
GeNN works fine on CPU and, for small models, it's pretty fast but I suspect, without GPU, the mnist mushroom body tutorial we're going to use for the second half of the session will be too slow.

**Comment by tnowotny** [comment]
I think the tutorial was alright. Ankur, what do we do with the recording? Also, should I record an Intro separately or should we let that lie?

**Comment by tnowotny** [comment]
Ok, here is the video:
https://sussex.box.com/s/2r7rp7nhrjria2b6vag9jevldnkae1n9
I have not recorded the intro again - I think it is fine without it.

**Comment by sanjayankur31** [comment]
Thanks very much. I've added these links to the public and private docs now.

**Comment by sanjayankur31** [comment]
Recordings have been added to page, closing. I'll reach out to tutors over e-mail for feedback etc.
