### ISSUE TITLE
CNS*2022 satellite tutorial: arbor

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#78]
@brenthuisman @clinssen : it'll be great to have a satellite tutorial on arbor: what do you think?

**Comment by sanjayankur31** [comment]
arbor have also put in a proposal for in-person tutorial at Melbourne with NEST etc., so we'll leave this open and see what folks want to do once the proposals have been accepted.

**Comment by brenthuisman** [comment]
Yes, sure, a satellite tutorial is OK! The usual format I do is about 3 hours.

To be quite honest, I don't recall setting up anything w.r.t. a tutorial in Melbourne (I'm unable to travel) but @Helveg has applied for a posterpresentation of some Arbor work. Is that what you mean?

**Comment by sanjayankur31** [comment]
I think I may have conflated the NEST and arbor sessions as one huge full day session at Melbourne. Sorry about that. 

3 hours would be great. Here's the other bits of info we're asking for currently to be able to draft up a schedule:

```
In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.
```

**Comment by brenthuisman** [comment]
I'll write my reply here, if I need to send it somewhere else, let me know.

Expected duration: 3 hours / half day.
Preferred start time: 7am-12am UTC
Blocked days: no.
Zoom room: Yes (we have an institutional BigBlueButton, but screen share isn't great there).

Webpage/post will follow.

**Comment by sanjayankur31** [comment]
thanks very much, I think we're OK using this ticket here for all the bits if that works for you, just to keep everything in one place (also for everyone to follow)

**Comment by sanjayankur31** [comment]
Hi @brenthuisman I've published the schedule on our website [here](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html), and we'll publish the Zoom links in a different document whose link we'll send out in the registration confirmation e-mail.

I've set up a zoom meeting for you using my institutional zoom account (no authentication required to attend it, but I can enable some security measures like requiring a zoom login if you want?). Is `b.huisman AT fz-juelich DOT de` the e-mail address I should send you the link at?

Could you a set up web page and tell me link? I think that's the last bit that remains now.

**Comment by sanjayankur31** [comment]
@brenthuisman : I've started the zoom call for the arbor session now

**Comment by brenthuisman** [comment]
I looks like I may have never received the link myself. I'll approach you on Gitter/Matrix.

**Comment by sanjayankur31** [comment]
Recordings have been added to page, closing. I'll reach out to tutors over e-mail for feedback etc.
