### ISSUE TITLE
CNS*2022 satellite tutorial: EBRAINS Services (e.g. Live Papers)

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#79]
I am up for conducting a mini-tutorial (1.5 hours?) on EBRAINS Live Papers. This could even be a hands-on session where each participant actively develops an actual Live Paper pertaining to their work/publication.

For more info on Live Papers, check: https://live-papers.brainsimulation.eu/

I could try to rope in owners/devs of other EBRAINS services and have a session comprising of 2-4 of such tools/services.
Let me know your thoughts on this.

**Comment by sanjayankur31** [comment]
Dropping this here for you too @appukuttan-shailesh :)

In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

**Comment by sanjayankur31** [comment]
Hi @appukuttan-shailesh @lbologna @rcsm17 @antonelepfl: I have a draft schedule here with the EBRAINS session slotted for Tuesday 28th June at 0800 UTC (1000 CEST). Could you please check and let me know if this works for you or not?

https://docs.google.com/spreadsheets/d/1F63MAfV_ofSHPeL_cltC0T_SpQqHeMIIokIjEua-KTY/edit?usp=sharing

**Comment by sanjayankur31** [comment]
Thanks very much @lbologna. I've marked your session as confirmed in the spreadsheet now.

**Comment by appukuttan-shailesh** [comment]
Sorry for my late response. The proposed schedule works well for me too.
I will setup a webpage with session details by end of this week.

**Comment by appukuttan-shailesh** [comment]
Webpage ready:
https://wiki.ebrains.eu/bin/view/Collabs/cns-2022-ebrains-session/

**Comment by sanjayankur31** [comment]
Thanks, doc for registrants updated too.

**Comment by appukuttan-shailesh** [comment]
Recording has been shared.
