### ISSUE TITLE
CNS*2022 satellite tutorial: Brain Dynamics Toolbox

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#81]
@stewart-heitmann : it'll be very useful to have a satellite tutorial on the Brain Dynamics Toolbox. What do you think?

**Comment by sanjayankur31** [comment]
@stewart-heitmann has said they're doing a showcase, and will probably not do a tutorial

**Comment by stewart-heitmann** [comment]
Hi @sanjayankur31 . Yes I am doing a showcase. So no software tutorial.
