### ISSUE TITLE
CNS*2022 satellite tutorial: NetPyNE

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#84]
Sessions on NEURON/NetPyNE would be great, and the dev teams have indicated that they are happy to do them.

Note that sessions for NEURON/NetPyNE have also been submitted to the in-person meeting.

**Comment by sanjayankur31** [comment]
@joewgraham tagging you here just so someone from the dev team gets updates :P

**Comment by sanjayankur31** [comment]
@salvadord @joewgraham 

In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

**Comment by sanjayankur31** [comment]
(Also e-mailed)

**Comment by salvadord** [comment]
Hi Ankur, here are the responses:

- what is the expected duration of the session? 6-7 hours
- what is the preferred start time of the session (in UTC)? 1pm UTC
- are there days that you cannot hold the session in the June 27--July 1 interval? June 27 might not work.
- would you like us to set up zoom meeting rooms for you (for organisers that may not have access to institutional zoom etc. subscriptions)? No, have my own zoom account

thanks!

**Comment by sanjayankur31** [comment]
Thanks very much. We'll have a draft schedule up once we have everyone's responses.

**Comment by sanjayankur31** [comment]
Hi @salvadord : just double-checking: would you still be needing 6--7 hours for the NetPyNE session (now that the NEURON session is running separately)?

**Comment by salvadord** [comment]
Hi @sanjayankur31 I think we can do still 6 hours since would like to have some breaks and need enough time for the students to do hands-on exercises. Also, I think there's enough topics we can cover, here's a tentative list (many from the 2-week course we did last year):

Intro
NEURON basics
GUI tutorial 1 (simple net)
GUI tutorials 2+3 (detailed morph and RxD nets)
GUI param exploration tutorial
OSB workspaces, JupyterLab and importing NeuroML 
Jupyter NB tutorials 
Jupyter NB param optimization
Hands-on exercises
NetPyNE data structures and importing cell models
Analysis and plotting (including LFP and EEG)

**Comment by sanjayankur31** [comment]
Thanks, that sounds good. I've booked 7 hours for the NetPyNE session in the schedule draft. I'm just waiting on other wg members to check it before sending it out to you all to double-check your slots.

**Comment by sanjayankur31** [comment]
I'll post regular updates on number of registrations and who intends to attend what so all tutors can prepare accordingly on this ticket here---please keep an eye on it: #106

**Comment by sanjayankur31** [comment]
Hi @salvadord Could you please set up a zoom meeting and a web page (optional) and send me the links privately via e-mail at ankursinha AT fedoraproject DOT org when you have some time to spare please? If you don't have institutional access to a zoom like platform, I can also set a zoom meeting up for you, please let me know.

CC: @appukuttan-shailesh

**Comment by salvadord** [comment]
@sanjayankur31 I changed the zoom link to avoid using my personal room:  https://zoom.us/j/92430215843 

I also created a website for the tutorial, which I will share around today in social nets etc: http://dura-bernal.org/netpyne-online-tutorial-2022

**Comment by sanjayankur31** [comment]
Thanks, doc updated.

**Comment by salvadord** [comment]
hey ankur is there any way I can check how many people register? we are trying to estimate how many OSB resources will be needed for tomorrow...

**Comment by sanjayankur31** [comment]
Recordings have been added to page, closing. I'll reach out to tutors over e-mail for feedback etc.
