### ISSUE TITLE
WG website should permit copying of displayed content

### ISSUE THREAD

**Issue by appukuttan-shailesh** [OCNS/SoftwareWG#85]
A minor ticket... our webpage:
https://ocns.github.io/SoftwareWG/

Currently does not allow right-click copy of content.
This oftens makes it a tad difficult to copy useful info over, and share them with people.
(have to resort to accessing the page source code whenever doing this)

@sanjayankur31 : do we have strong reasons for keeping it so?

**Comment by sanjayankur31** [comment]
No, not at all. I hadn't noticed---it's probably something in the theme we're using, but not sure why they have this "feature" there either.

**Comment by sanjayankur31** [comment]
The theme's here, as a submodule:

**Comment by sanjayankur31** [comment]
Ah, hold on, I already fixed it. I just made the mistake of using the `master` branch of the submodule instead of our branch after my latest update. Fixing that now.

**Comment by sanjayankur31** [comment]
Corrected the submodule branch now, should be fixed in https://github.com/OCNS/SoftwareWG/commit/21af145e2f784168903d09292f287ddc82f57fc6 which is building/deploying now.

**Comment by sanjayankur31** [comment]
I was wondering where the "share post" buttons had gone :laughing: . It all makes sense now.
