### ISSUE TITLE
CNS*2022 satellite tutorials: scheduling etc.

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#86]
@OCNS/software-wg : this ticket is for us to organise the sessions---schedules etc.

From what we've discussed previously:

- we have 5 full days (June 27--July 1)
- we are not time zone bound
- we would like to minimise overlaps to allow attendees to attend as many sessions as they can
- these are free, so we hope to attract large numbers (like we did at the free online CNS conferences).

I suggest that we loosely mirror the in-person tutorial format:

- "half day tutorials": 3--4 hours (with break every 2 hours)
- "full day tutorials": 6--8 hours (with break every 2 hours)
- additionally, single sessions: ~2 hours?

Also similar to the in-person meeting, we can aim to limit ourselves to 4 concurrent sessions in parallel at most. (That still gives us a total of ~20 full day tutorials at most over five days at maximum, or we can fit more/less but well spaced out sessions if they're not all full day.)

For reference:

- [CNS 2022 Call for Tutorials](https://ocns.memberclicks.net/cns-2022-call-for-tutorials)
- [CNS 2021 Tutorials](https://ocns.memberclicks.net/cns-2021-tutorials)
- [CNS 2020 Tutorials](https://ocns.memberclicks.net/cns-2020-tutorials)
- [CNS 2019 Tutorials](https://ocns.memberclicks.net/cns-2019-tutorials) : 9 tutorials in a day at the previous in-person meeting!

How does this sound? Thoughts?

**Comment by sanjayankur31** [comment]
The lengths sounds good. So if no one has any objections/comments/better ideas, I propose we go with Shailesh's suggestions:

- short tutorials (1.5 - 2 hours)
- half-day tutorials (3 hours)
- full-day tutorials (2 x 3 hours)

Of course, these will be suggested to dev teams and they will have the flexibility to tweak these to better organise their sessions.

+1 to reduce overlapping as much as possible---should be doable over 5 days.

+1 to doing tutorials all year, but given that we also want to keep doing dev sessions, and software highlights, and have stuff already in the pipeline for the INCF meetings, unless we have more folks to spread the work, I worry that they may not materialise---which is why if we're putting in the effort to set up satellite tutorials, I'd like to do as many as we can given our chosen constraints :)

**Comment by sanjayankur31** [comment]
Let's time box this---let's aim to get to a decision by Wednesday, 4th May. @OCNS/software-wg : please let us know what you think (please comment even if you think this is OK and have nothing to add, so we know that you have taken a look at this proposal).

**Comment by kernfel** [comment]
Durations and low to no overlap sounds good. As for year round tutorials, I guess there's always room to repeat things at minimal cost, if presenters are willing and there's a potential audience.

**Comment by sanjayankur31** [comment]
Based on what we discussed at the meeting, this is what' I'm e-mailing out to organisers:

```
In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

```

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg 

Based on the inputs from all the organisers (see all the tickets), I've set up a preliminary schedule here:

https://docs.google.com/spreadsheets/d/1F63MAfV_ofSHPeL_cltC0T_SpQqHeMIIokIjEua-KTY/edit?usp=sharing

Could you all please go through it to check that:

- I've not missed a sesssion
- I've taken everyone's requirements/restrictions into account?


If you could please do this by end of tomorrow (Tuesday), I'll I'll send it out to all the tutors to double-check

**Comment by tnowotny** [comment]
The schedule is good for the GeNN-team.

**Comment by sanjayankur31** [comment]
I've moved NetPyNE to make space for the NEURON tutorial session. Waiting for tutors to confirm.

**Comment by brenthuisman** [comment]
Looks good to me!

**Comment by tnowotny** [comment]
just saw the announcement on the WG mailing list - when do you think is a good time to send announcements to comp-neuro, connectionists and the like?
Also, social media ...?

**Comment by sanjayankur31** [comment]
I've sent them to comp-neuro/neuroinfo/systems-neuro/connectionists too, but they're awaiting moderation there. Should hopefully get through in the next couple of days.

We can probably start with social media already, and then send out a new announcement once the schedule is ready?

I've made a quick post on Twitter here:

https://twitter.com/sanjay_ankur/status/1531624262003564545?s=20&t=BSx0gbHSUPuirPDgn-aifg

**Comment by caglorithm** [comment]
✅ We can do a 1.5-2 hrs session at 13:30 UTC! Really appreciate you for organizing everything!

**Comment by mstimberg** [comment]
I think you already had my general ok, but just to confirm again that the Brian tutorial times work for us. Thanks again for setting all this up :pray:

**Comment by sanjayankur31** [comment]
Thanks for confirming @mstimberg , I've marked it in the spreadsheet too now.

**Comment by sanjayankur31** [comment]
We've received confirmation from a majority of tutors, so that schedule is looking good. Closing this now.
