### ISSUE TITLE
CNS*2022 satellite tutorial: MOOSE

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#87]
The MOOSE development team would be happy to host a session also.

**Comment by sanjayankur31** [comment]
Response:

- 2 slots of 1.5-2hour each if possible to repeat the session and cover more time zones. 
- 8pm to 10pm ISD (1530 UTC) 
- 10.30-12AM ISD (0600 UTC)

I've noted that it should be fine to do two slots because these are short tutorials, but it will depend on how much overlap there is between sessions.

**Comment by sanjayankur31** [comment]
Hi @hrani @upibhalla: I've published the schedule on our website [here](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html), and we'll publish the Zoom links in a different document whose link we'll send out in the registration confirmation e-mail.

Could you please set up a zoom meeting and a web page (optional) and send me the links privately via e-mail at ankursinha AT fedoraproject DOT org when you have some time to spare please? If you don't have institutional access to a zoom like platform, I can also set a zoom meeting up for you, please let me know.

**Comment by upibhalla** [comment]
Dear Ankur,

Thank you for setting this up. I'm currently travelling so it may take a 
little while to set up a suitable web page, but I'll request Harsha to 
think about that.

Here are the zoom links.

Best,

Upi


Upi Bhalla is inviting you to a scheduled Zoom meeting.

Topic: MOOSE Tutorial 1
Time: Jun 27, 2022 09:30 PM Mumbai, Kolkata, New Delhi

Join Zoom Meeting
https://zoom.us/j/92282201299?pwd=d2RoOHpUR0pGdGFlK2EzZjZaS2lHQT09

Meeting ID: 922 8220 1299
Passcode: 115906


Upi Bhalla is inviting you to a scheduled Zoom meeting.

Topic: MOOSE Tutorial 2
Time: Jun 28, 2022 11:30 AM Mumbai, Kolkata, New Delhi

Join Zoom Meeting
https://zoom.us/j/97486455352?pwd=cEozRUQxVnQwbTdJNmJ5cVFNV3RkQT09

Meeting ID: 974 8645 5352
Passcode: 600559

**Comment by sanjayankur31** [comment]
I'll post regular updates on number of registrations and who intends to attend what so all tutors can prepare accordingly on this ticket here---please keep an eye on it: #106

**Comment by hrani** [comment]
Dear Ankur,
Sorry for the delay, could you put this link in the website 
https://moose.ncbs.res.in/cns2022_moose/

**Comment by pgleeson** [comment]
Done @hrani.

**Comment by sanjayankur31** [comment]
Thanks @pgleeson !

**Comment by hrani** [comment]
Dear Ankur,
Let us know to which email id we need to send the recording of the moose
tutorial.
Harsha

**Comment by sanjayankur31** [comment]
You can send it to `ankursinha AT fedoraproject DOT org`. Thanks.
