### ISSUE TITLE
Dev session: NetPyNE

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#9]
Tracker ticket: 

A dev session on NetPyNE would be great!

http://www.netpyne.org/

**Comment by sanjayankur31** [comment]
Hi @joewgraham 

I see a couple of new NetPyNE releases recently. Would you be up for a dev session in the comings weeks by any chance?

**Comment by joewgraham** [comment]
I would love to do a dev session on NetPyNE soon.  Let's schedule one.

I actually just stepped down from my official position at NetPyNE (the recent releases were partially me wrapping up all the loose ends I had created over the last two years).  I will continue working on NetPyNE as needed as a consultant/contractor.

That said, I'd love to summarize what I dev'ed at NetPyNE, if people are interested.  Specifically I'd talk about (1) documentation (using docstrings in the code, Sphinx, Napoleon, and autodocsumm to generate html documentation) and (2) analysis and plotting (separating the two and standardizing using new MetaFigure and Plotter classes).

**Comment by sanjayankur31** [comment]
Sounds good. Yeh, a session on your work and what's new in the latest releases would be awesome. When would you like to do it? I think we usually do dev sessions around 1600/1700 UTC?

CC: @OCNS/software-wg so folks can check if the time works for them etc.

**Comment by joewgraham** [comment]
Any day during the week of April 4 - 8 would work for me, and 1600 or 1700 UTC is fine.  Any preferences on the day?

**Comment by sanjayankur31** [comment]
I can do Mon/Thu/Fri that week. @OCNS/software-wg : what about everyone else?

**Comment by appukuttan-shailesh** [comment]
I think better to avoid a Friday evening.... lets go with Mon or Thu.

**Comment by mstimberg** [comment]
> I think better to avoid a Friday evening.... lets go with Mon or Thu.

Agree, and both would work for me.

**Comment by sanjayankur31** [comment]
Let's do Monday then? @joewgraham would you write up an abstract that we can send out and put on the website? I'll go set up a zoom meeting for us

**Comment by sanjayankur31** [comment]
That sounds great. It'll be good to have the post on the software wg website and the e-mails to MLs out latest by Friday morning so that folks at least have a two working day notice about the session.

**Comment by joewgraham** [comment]
Hey @sanjayankur31 , I'm getting my abstract uploaded now, but I don't have access to a paid Zoom account.  Can someone else set one up?  Or should I create a Google Meet?

**Comment by sanjayankur31** [comment]
I created one. Here's the invite, I'll go update the blog post:

```
Ankur Sinha (he/him/his) is inviting you to a scheduled Zoom meeting.

Topic: INCF/OCNS Software WG: Joe Graham: NetPyNE
Time: Apr 4, 2022 04:00 PM Universal Time UTC

Join Zoom Meeting
https://ucl.zoom.us/j/99620419452?pwd=SkZlQnJmWWZVczNURkp2azVOZkhzUT09

Meeting ID: 996 2041 9452
Passcode: 610187
One tap mobile
+12532158782,,99620419452#,,,,*610187# US (Tacoma)
+13017158592,,99620419452#,,,,*610187# US (Washington DC)

Dial by your location
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
Meeting ID: 996 2041 9452
Passcode: 610187
Find your local number: https://ucl.zoom.us/u/adF3SKr4E

```

Please note that one must login to zoom to attend, to prevent spammers.

@joewgraham should I announce the session on the lists or would you prefer to do that?

**Comment by sanjayankur31** [comment]
Great. I'll do that ASAP.

**Comment by sanjayankur31** [comment]
Sent to all the MLs.

@joewgraham looks like the netpyne ML has blocked posting by e-mail? I get: 

```
The response was:
The group netpyne-mailing@googlegroups.com does not allow posting through email.
```

**Comment by sanjayankur31** [comment]
fixed---had to mail netpyne-forum, not netpyne-mailing.

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg , reminder for the session later today at 1600 UTC. Please also spread the word. Here's the announcement on Twitter:

https://twitter.com/sanjay_ankur/status/1510966581299494917?s=20&t=ChE-rz3wLnVadWIWBbS7gA

**Comment by sanjayankur31** [comment]
I've started the zoom call now folks, please join when convenient @OCNS/software-wg

**Comment by sanjayankur31** [comment]
Recording information:

```
Topic: INCF/OCNS Software WG: Joe Graham: NetPyNE
Start Time: Apr 4, 2022 04:48 PM

Meeting Recording:
https://ucl.zoom.us/rec/share/FJ6vNZq6tFnq5OgnGmvc6Y1i09L7gUjIlqN_p3BrIl-IFjWDaPooMSf963VZhI2J.p4pLIbDmQwdIE7dU

Access Passcode: %xm8K=t+
```

**Comment by sanjayankur31** [comment]
Forwarded to Heather for archival too now. We'll close this once they've been uploaded and we've updated the blog post with links.

**Comment by sanjayankur31** [comment]
https://ocns.github.io/SoftwareWG/2022/04/04/dev-session-joe-graham-netpyne.html
