### ISSUE TITLE
Next WG meeting: Monday 9th May, 2022: 0800 UTC + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#90]
Hi @OCNS/software-wg 

The next WG meeting is on the 9th of May. Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend *whichever one suits you best*. (You *do NOT* have to attend both!). Please see #66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://ocns.github.io/SoftwareWG/2022/04/21/wg-meeting-11-april-2022.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by appukuttan-shailesh** [comment]
Intending to attend the 0800 UTC meeting.

**Comment by sanjayankur31** [comment]
Hi @OCNS/software-wg 

Reminder of our 0800 UTC meeting in ~45 minutes

Here's the Jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

See you all in a bit :)

**Comment by sanjayankur31** [comment]
Minutes for the meeting are being collected here:

https://hackmd.io/s/BySwvHIU5

**Comment by sanjayankur31** [comment]
Thanks for coming everyone. If you weren't able to attend either session, please go through the logs here and drop any comments you have in this ticket:

https://hackmd.io/s/BySwvHIU5

I'll send these out to the mailing list now. Please subscribe if you haven't yet.

https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg

**Comment by kernfel** [comment]
Apologies for my absence, was away travelling and hadn't put the meeting in my calendar. From now on, though...

> ACTION: introduce WG in all satellite sessions: request presenters to do a quick blurb on WG to start with

Are all presenters also WG members? If not, it might be better to drop in one of us as quasi-hosts to introduce the WG and open the session.

**Comment by sanjayankur31** [comment]
Yes, that'll be very good to do :+1: . Once we have the schedule drafted, we can try and distribute ourselves over the different sessions. We're also offering zoom rooms to organisers, so a few of us will be around as hosts anyway.
