### ISSUE TITLE
D&I session at INCF assembly

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#91]
@OCNS/software-wg 

A session on diversity and inclusion that we'll organise has been accepted at the INCF Assembly in September.

It's going to be a traditional session with talks and panel discussion. Initial thoughts/planning is here:

https://hackmd.io/s/SJgYACqQ9

If this is something that interests you, please do get involved and help us organise it. All ideas are welcome, either here on this ticket or in the hackmd doc.

**Comment by malinINCF** [comment]
Thanks for pinging me in. I suggest we start thinking about possible discussion points - I have added a few suggestions and a few links to relevant papers in the planning doc.

**Comment by sanjayankur31** [comment]
This is now ready. I'll close it after I share notes from the session.

**Comment by sanjayankur31** [comment]
Recordings from the session can now be seen here:

https://training.incf.org/lesson/diversity-and-inclusion-neuroinformatics

I *strongly* recommend that everyone watch them. We had a great set of speakers, and there was a lot of information that gave us all a lot to think about :)
