### ISSUE TITLE
Software arena session at the INCF assembly 2022

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#92]
@OCNS/software-wg : A "software arena" session has been accepted at the INCF assembly in September. It's an informal "birds of a feather" session. Here's what we'd submitted:

## Abstract
Contemporary neuroscience is heavily reliant on computing. From computational modelling to the analysis of data gathered from experiments, all tasks in the neuroscience research pipeline require a basic knowledge of common computing tools. Yet, the multi-disciplinary nature of neuroscience research implies that many of us do not hail from computing disciplines, and therefore have not received formal training in this area.
Keeping in line with its goal of improving technical software/computing knowledge in the research community, the INCF/OCNS Software working group (WG) will conduct a session aiming to:
- providing more visibility to all the software that is out there for neuroinformatics / neuroscience research
- discussing best practices that help in development and long term maintenance of software tools
- identifying potential pitfalls that tool developers are likely to encounter, e.g. shortcuts that lead to greater issues down the line
- emphasis on how testing should not be a post facto activity, but rather go hand-in-hand with software development
- discuss the importance of software documentation and effective ways of handling it

## Format/speakers

For a 1.5 hour workshop, perhaps we can limit it to short “show and tell” / “lightening” talks where people take the “stage” for 3--5 minutes to do quick blurbs on their/a software, and combine it with more focused discussions on the topics listed above.

------

If this interests you, please participate in the organisation by dropping any thoughts/comments here on the ticket :)

**Comment by appukuttan-shailesh** [comment]
I am going to be a bit under the radar for the next couple of months. Can some others volunteer to help coordinate this 1-hour session at the [INCF Assembly 2022](https://neuroinformatics.incf.org/2022/sessions) (Sep 16-20)?
@OCNS/software-wg

**Comment by appukuttan-shailesh** [comment]
Hello @OCNS/software-wg  members,

Just a reminder that we are need a chair/organizer for this session. I will not be available for the INCF assembly and @sanjayankur31 already has his hands full. Would be great if somebody else could volunteer to take this up.
If nobody is available, we might need to cancel the session.

**Details:** https://neuroinformatics.incf.org/2022/sessions
see "Software arena (tool developers BoF)" session
Sep 16-20
