### ISSUE TITLE
Next WG meeting: Tuesday 14th June, 2022: 0800 UTC + 1700 UTC

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#98]
Hi @OCNS/software-wg 

The next WG meeting is on the 14th June. Please note that there will be two meetings, one at 0800 UTC and another at 1700 UTC and you can attend whichever one suits you best. (You do NOT have to attend both!). Please see https://github.com/OCNS/SoftwareWG/issues/66 for a discussion on this.

The meeting will be on Jitsi again. Here's the link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

Meeting minutes from last month's meeting are here:

https://ocns.github.io/SoftwareWG/2022/05/23/wg-meeting-09-may-2022.html

Please comment on this ticket:

- to note any items you'd like to discuss
- to note which meeting session you are likely to attend (so we have some idea of numbers)
- if you are unable to attend either slot

**Comment by sanjayankur31** [comment]
Agenda item: update on CNS*2022 satellite tutorials. Please see the milestone here for tickets and progress:

https://github.com/OCNS/SoftwareWG/milestone/3

**Comment by sanjayankur31** [comment]
@OCNS/software-wg : reminder for the meetings(s) on Monday. Please let us know here what session you're more likely to attend (or if you're unable to attend at all).

See you all on Monday!

Jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Er, on Tuesday! (corrected)

**Comment by appukuttan-shailesh** [comment]
I would unfortunately not be able to attend either of the sessions this time. I am back from holidays but leaving for a workshop tomorrow morning, and so will be unavailable till Friday. Will follow the minutes of the meeting to stay informed.

**Comment by sanjayankur31** [comment]
Reminder of the meeting folks, starting in ~30 minutes. 

Jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Reminder of the second meeting folks, starting in ~5 minutes.

Jitsi link:

https://meet.jit.si/moderated/27ddeaff25933944fea1937f182235d48de7c2dd59dc2f84f8eebb26a8fc07ab

**Comment by sanjayankur31** [comment]
Minutes are being noted here: https://hackmd.io/@sanjayankur31/SykigaHKc

**Comment by sanjayankur31** [comment]
MInutes published:

https://ocns.github.io/SoftwareWG/2022/07/07/wg-meeting-14-june-2022.html
