### ISSUE TITLE
New mailing list! Subscribe!

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/SoftwareWG#99]
@OCNS/software-wg : please subscribe to the mailing list to ensure you get all updates about the WG.

You can subscribe here:

https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg

If you have any trouble subscribing, please let us know here in this ticket.

**Comment by sanjayankur31** [comment]
More information on the new list in this post:

https://ocns.github.io/SoftwareWG/2022/04/22/new-announcement-mailing-list-for-the-wg.html

**Comment by appukuttan-shailesh** [comment]
Having trouble accessing the mailing list webpage:
https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg

Can someone else test?

**Comment by mstimberg** [comment]
> Having trouble accessing the mailing list webpage: https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg

The website times out for me as well.

**Comment by tnowotny** [comment]
Hi,
I can confirm that it does not seem to work.
Best, Thomas

--
Prof. Thomas Nowotny
Head of AI Research Group
CCNR, Sussex Neuroscience             Phone: +44-1273-678593
Engineering and Informatics,                Fax: +44-1273-877873
University of Sussex,
Falmer, Brighton BN1 9QJ      sussex.ac.uk/informatics/tnowotny<http://sussex.ac.uk/informatics/tnowotny> <../../owa/redir.aspx?C=9e11bb0e527242938402b42d9b5498ea&URL=http%3a%2f%2fsussex.ac.uk%2finformatics%2ftnowotny>

I support the University of Sussex Community Pledge, as I continue to help those around me during the pandemic.  Small acts of collaboration, kindness and integrity can make a big difference.  www.sussex.ac.uk/community-pledge<http://www.sussex.ac.uk/community-pledge>
________________________________

**Comment by sanjayankur31** [comment]
ML web interface is back up.
